export const printableRegistrationFormCopy = {
  ar: {
    title: "استمارة تسجيل طالب جديد",
    subtitle: "نموذج ورقي لجمع بيانات الطالب وولي الأمر قبل إدخالها في المنصة",
    school: "المدرسة",
    schoolPlaceholder: "اسم المدرسة",
    formNumber: "رقم الاستمارة",
    applicationDate: "تاريخ استلام الاستمارة",
    requiredNote: "الحقول المعلّمة بنجمة (*) مطلوبة لإتمام التسجيل في المنصة.",
    studentSection: "القسم الأول — بيانات الطالب",
    studentInstruction: "يملأ الطالب أو ولي أمره البيانات التالية بخط واضح",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    birthDate: "تاريخ الميلاد",
    gender: "الجنس",
    male: "ذكر",
    female: "أنثى",
    nationalId: "رقم الهوية",
    studentPhone: "هاتف الطالب",
    studentEmail: "البريد الإلكتروني للطالب",
    address: "العنوان الكامل",
    previousSchool: "المؤسسة التعليمية السابقة",
    educationStage: "المرحلة الدراسية",
    educationYear: "السنة / المستوى",
    optional: "اختياري",
    studentSignature: "توقيع الطالب",
    pageOne: "الصفحة ١ من ٢",
    guardianSection: "القسم الثاني — بيانات ولي الأمر",
    guardianInstruction: "يملأ ولي الأمر هذا القسم، وتُستخدم بيانات الاتصال للتواصل بشأن الطالب",
    guardianName: "الاسم الكامل لولي الأمر",
    guardianRelation: "صلة القرابة",
    guardianPhone: "رقم هاتف ولي الأمر",
    guardianEmail: "البريد الإلكتروني لولي الأمر",
    guardianJob: "المهنة",
    additionalGuardian: "ولي أمر إضافي (اختياري)",
    additionalGuardianNote: "يمكن تسجيل هذا الولي لاحقًا من دليل الأولياء في المنصة.",
    additionalGuardianName: "اسم ولي الأمر الإضافي",
    additionalGuardianRelation: "صلة القرابة",
    additionalGuardianPhone: "رقم الهاتف",
    admissionSection: "يُستكمل من مكتب التسجيل",
    branch: "الفرع",
    className: "الحلقة / الفوج",
    startDate: "تاريخ بدء الدراسة",
    documentsSection: "الوثائق المرفقة",
    birthCertificate: "شهادة الميلاد",
    personalPhotos: "صور شخصية",
    medicalReport: "تقرير طبي",
    previousCertificate: "شهادة مدرسية سابقة",
    attached: "مرفقة",
    notAttached: "غير مرفقة",
    guardianDeclaration: "أؤكد أن البيانات التي دوّنتها صحيحة حسب علمي، وأتعهد بإبلاغ المدرسة عند تغيّر معلومات التواصل.",
    guardianSignature: "توقيع ولي الأمر",
    receivedDate: "التاريخ",
    officeNotes: "ملاحظات مكتب التسجيل",
    enteredBy: "أُدخلت البيانات بواسطة",
    studentNumber: "رقم ملف الطالب",
    privacyNote: "تُستخدم هذه البيانات لإنشاء ملف الطالب والتواصل بشأن دراسته، وتحفظها المدرسة بسرية. لا تكتب أي كلمة مرور في هذه الاستمارة.",
    pageTwo: "الصفحة ٢ من ٢",
    print: "طباعة الاستمارة",
    back: "العودة إلى تسجيل الطالب",
    printHint: "يمكن الطباعة مباشرة أو اختيار «حفظ بصيغة PDF» من نافذة الطباعة.",
  },
  en: {
    title: "New Student Registration Form",
    subtitle: "Paper form to collect student and guardian details before entering them in the platform",
    school: "School",
    schoolPlaceholder: "School name",
    formNumber: "Form number",
    applicationDate: "Date received",
    requiredNote: "Fields marked with an asterisk (*) are required to complete registration in the platform.",
    studentSection: "Section 1 — Student details",
    studentInstruction: "To be completed by the student or their guardian in clear handwriting",
    firstName: "First name",
    lastName: "Last name",
    birthDate: "Date of birth",
    gender: "Gender",
    male: "Male",
    female: "Female",
    nationalId: "National ID",
    studentPhone: "Student phone",
    studentEmail: "Student email",
    address: "Full address",
    previousSchool: "Previous school",
    educationStage: "Education stage",
    educationYear: "Year / level",
    optional: "Optional",
    studentSignature: "Student signature",
    pageOne: "Page 1 of 2",
    guardianSection: "Section 2 — Guardian details",
    guardianInstruction: "To be completed by the guardian. Contact details are used for student-related communication.",
    guardianName: "Guardian full name",
    guardianRelation: "Relationship to student",
    guardianPhone: "Guardian phone",
    guardianEmail: "Guardian email",
    guardianJob: "Occupation",
    additionalGuardian: "Additional guardian (optional)",
    additionalGuardianNote: "This guardian can be added later from the Guardians directory in the platform.",
    additionalGuardianName: "Additional guardian name",
    additionalGuardianRelation: "Relationship",
    additionalGuardianPhone: "Phone",
    admissionSection: "For the registration office",
    branch: "Branch",
    className: "Class / cohort",
    startDate: "Study start date",
    documentsSection: "Documents provided",
    birthCertificate: "Birth certificate",
    personalPhotos: "Personal photos",
    medicalReport: "Medical report",
    previousCertificate: "Previous school certificate",
    attached: "Attached",
    notAttached: "Not attached",
    guardianDeclaration: "I confirm that the information provided is accurate to the best of my knowledge and will notify the school if my contact details change.",
    guardianSignature: "Guardian signature",
    receivedDate: "Date",
    officeNotes: "Registration office notes",
    enteredBy: "Entered by",
    studentNumber: "Student file number",
    privacyNote: "This information is used to create the student record and communicate about their studies, and will be kept confidential by the school. Do not write any password on this form.",
    pageTwo: "Page 2 of 2",
    print: "Print form",
    back: "Back to student registration",
    printHint: "Print directly or choose “Save as PDF” in the print dialog.",
  },
} as const;
