// English copy for legacy operational screens that still render Arabic source
// strings. Keeping the catalog separate makes coverage measurable and prevents
// page components from accumulating one-off language conditionals.
export const EXACT_UI_ENGLISH: Record<string, string> = {
  // Student creation
  "إضافة طالب جديد": "Add new student",
  "البيانات الأساسية والصورة": "Basic information and photo",
  "الاتصال والتعليم": "Contact and education",
  "المراجعة والتأكيد": "Review and confirmation",
  "الخطوة": "Step",
  "التالي": "Next",
  "حفظ وتأكيد": "Save and confirm",
  "العودة للطلاب": "Back to students",
  "هذا الحقل مطلوب": "This field is required",
  "تنبيه": "Warning",
  "لديك بيانات غير محفوظة. هل تريد المغادرة؟": "You have unsaved changes. Do you want to leave?",
  "نعم، غادر": "Yes, leave",
  "ابقَ هنا": "Stay here",
  "الاسم الأول": "First name",
  "اسم العائلة": "Last name",
  "تاريخ الميلاد": "Date of birth",
  "رقم الهوية": "ID number",
  "صورة الطالب": "Student photo",
  "صورة خاصة غير عامة. JPG أو PNG أو WebP بحد أقصى 5MB.": "Private, non-public photo. JPG, PNG, or WebP up to 5 MB.",
  "اختيار صورة": "Choose photo",
  "إزالة الصورة": "Remove photo",
  "غير مرفقة": "Not attached",
  "رقم الهاتف": "Phone number",
  "المؤسسة التعليمية / السابقة": "Current / previous school",
  "المرحلة الدراسية": "Education level",
  "السنة الدراسية": "School year",
  "ابتدائي": "Primary",
  "متوسط": "Middle school",
  "ثانوي": "Secondary",
  "جامعي": "University",
  "اختر السنة": "Choose year",
  "اختر المرحلة أولًا": "Choose the level first",
  "اسم ولي الأمر": "Guardian name",
  "صلة القرابة": "Relationship",
  "هاتف ولي الأمر": "Guardian phone",
  "بريد ولي الأمر": "Guardian email",
  "مهنة ولي الأمر": "Guardian occupation",
  "أب": "Father",
  "أم": "Mother",
  "أخ": "Brother",
  "أخت": "Sister",
  "عم": "Uncle",
  "عمة أو خالة": "Aunt",
  "جد": "Grandfather",
  "جدة": "Grandmother",
  "توقيت الحلقة": "Class schedule",
  "تاريخ البدء": "Start date",
  "بدون حلقة": "No class",
  "لا توجد حلقات نشطة في هذا الفرع": "There are no active classes in this branch",
  "جارٍ تحميل الفروع...": "Loading branches...",
  "جارٍ تحميل الحلقات...": "Loading classes...",
  "تعذر تحميل الفروع النشطة.": "Could not load active branches.",
  "تعذر تحميل حلقات الفرع.": "Could not load branch classes.",
  "شهادة الميلاد": "Birth certificate",
  "صور شخصية ورقية / إضافية": "Printed / additional personal photos",
  "تقرير طبي": "Medical report",
  "شهادة مدرسية سابقة": "Previous school certificate",
  "مراجعة البيانات": "Review information",
  "البيانات الأساسية": "Basic information",
  "معلومات الاتصال والتعليم": "Contact and education information",
  "معلومات ولي الأمر": "Guardian information",
  "معلومات الحلقة": "Class information",
  "مقدم": "Submitted",
  "غير مقدم": "Not submitted",
  "تم حفظ الطالب، لكن تعذر رفع الصورة.": "The student was saved, but the photo could not be uploaded.",
  "تعذر حفظ بيانات الطالب حاليًا.": "Could not save the student information right now.",
  "تمت إضافة الطالب بنجاح.": "Student added successfully.",
  "السنة": "Year",

  // Registration CRM
  "جديد": "New",
  "تم التواصل": "Contacted",
  "مؤهل": "Qualified",
  "زيارة مجدولة": "Visit scheduled",
  "بانتظار الوثائق": "Awaiting documents",
  "قائمة الانتظار": "Waitlist",
  "مقبول": "Accepted",
  "غير متابع": "Not followed up",
  "زيارة مباشرة": "Walk-in visit",
  "هاتف": "Phone",
  "الموقع": "Website",
  "شبكات اجتماعية": "Social media",
  "إحالة": "Referral",
  "حملة": "Campaign",
  "اكتمال الطاقة الاستيعابية": "Capacity reached",
  "الحلقة أو الفوج مكتمل": "Class or group is full",
  "عدم توافق التوقيت": "Schedule conflict",
  "فئة العمر مكتملة": "Age group is full",
  "وثائق ناقصة": "Missing documents",
  "بانتظار التقييم": "Awaiting assessment",
  "سبب آخر": "Another reason",
  "متابعة المهتمين بالتسجيل وقائمة الانتظار قبل إنشاء ملف الطالب النهائي.": "Follow registration prospects and the waitlist before creating the final student profile.",
  "طلب جديد": "New request",
  "إجمالي الطلبات": "Total requests",
  "طلبات جديدة": "New requests",
  "متابعات مستحقة": "Follow-ups due",
  "مقبولة": "Accepted",
  "بحث باسم الطالب أو الولي أو الهاتف...": "Search by student, guardian, or phone...",
  "لا توجد طلبات تسجيل مطابقة.": "No matching registration requests.",
  "الطالب المحتمل": "Prospective student",
  "المصدر": "Source",
  "المتابعة القادمة": "Next follow-up",
  "تحديث المتابعة": "Update follow-up",
  "إضافة طلب تسجيل": "Add registration request",
  "سجّل بيانات التواصل الأولية فقط. إنشاء الطالب يتم بعد القبول في مسار مستقل.": "Record initial contact details only. The student profile is created separately after acceptance.",
  "تاريخ الميلاد (اختياري)": "Date of birth (optional)",
  "الجنس (اختياري)": "Gender (optional)",
  "بريد ولي الأمر (اختياري)": "Guardian email (optional)",
  "ملاحظات": "Notes",
  "حفظ الطلب": "Save request",
  "تحديث مسار الطلب": "Update request stage",
  "أكمل الحقول المطلوبة.": "Complete the required fields.",
  "تم تسجيل طلب المتابعة.": "Follow-up request recorded.",
  "تم تحديث مسار الطلب.": "Request stage updated.",
  "تعذر حفظ طلب التسجيل حاليًا.": "Could not save the registration request right now.",
  "تعذر تحميل CRM التسجيل. أعد المحاولة.": "Could not load registration CRM. Try again.",
  "سبب الانتظار": "Waitlist reason",
  "المستوى أو الحلقة المطلوبة (اختياري)": "Requested level or class (optional)",
  "ترتيب الانتظار": "Waitlist position",
  "دخل القائمة": "Added to waitlist",
  "جارٍ تحميل طلبات التسجيل...": "Loading registration requests...",
  "(اختياري)": "(optional)",

  // Documents
  "إدارة الوثائق": "Document management",
  "وثائق خاصة للطلاب وطلبات التسجيل، محفوظة بصلاحيات الفرع فقط.": "Private student and registration documents, restricted to branch permissions.",
  "رفع وثيقة": "Upload document",
  "إجمالي الملفات": "Total files",
  "منتهية / قريبة": "Expired / expiring soon",
  "بحث بالاسم أو الملف أو الفرع...": "Search by name, file, or branch...",
  "كل الملفات": "All files",
  "لا توجد وثائق مطابقة.": "No matching documents.",
  "ناقصة": "Missing",
  "مرفوعة": "Uploaded",
  "مرفوضة": "Rejected",
  "منتهية": "Expired",
  "لم يرفع ملف بعد": "No file uploaded yet",
  "الصلاحية": "Validity",
  "بدون تاريخ انتهاء": "No expiry date",
  "تنزيل": "Download",
  "رفع أو استبدال وثيقة": "Upload or replace document",
  "الملف يبقى داخل التخزين الخاص ولا يُنشأ له رابط عام.": "The file remains in private storage and no public link is created.",
  "صاحب الوثيقة": "Document owner",
  "نوع الوثيقة": "Document type",
  "اسم الوثيقة الأخرى": "Other document name",
  "اختر PDF أو صورة بحد أقصى 10MB": "Choose a PDF or image up to 10 MB",
  "تاريخ الإصدار (اختياري)": "Issue date (optional)",
  "تاريخ الانتهاء (اختياري)": "Expiry date (optional)",
  "رفع وحفظ": "Upload and save",
  "تحديث حالة الوثيقة": "Update document status",
  "تعذر تحميل مركز الوثائق.": "Could not load the document center.",
  "تم حفظ الوثيقة بأمان.": "Document saved securely.",
  "تم تحديث حالة الوثيقة.": "Document status updated.",
  "تعذر تنفيذ العملية حاليًا.": "Could not complete the operation right now.",
  "اختر ملفًا صالحًا أولًا.": "Choose a valid file first.",
  "صور شخصية": "Personal photos",
  "هوية ولي الأمر": "Guardian ID",
  "استمارة التسجيل": "Registration form",
  "وثيقة أخرى": "Other document",
  "جارٍ تحميل الوثائق...": "Loading documents...",

  // Memorization workspace
  "بداية الآيات": "Starting verse",
  "نهاية الآيات": "Ending verse",
  "إنشاء السجل": "Create record",
  "تم حفظ السجل، وأصبح النموذج في وضع التعديل. اضغط «سجل جديد» لإضافة متابعة أخرى.": "Record saved and the form is now in edit mode. Select “New record” to add another follow-up.",
  "تم تحديث سجل المتابعة بنجاح.": "Follow-up record updated successfully.",
  "توجد نسخة أحدث من المنصة. أعد تحميل الصفحة قبل الحفظ لتجنب إنشاء سجل غير مقصود.": "A newer platform version is available. Reload before saving to avoid creating an unintended record.",
  "جارٍ تحميل نطاق متابعة الحفظ...": "Loading memorization access scope...",
  "تعذر تحميل متابعة الحفظ": "Could not load memorization follow-up",
  "تعذر التحقق من صلاحيات متابعة الحفظ حاليًا.": "Could not verify memorization permissions right now.",
  "لا توجد صلاحية لعرض متابعة الحفظ": "You do not have permission to view memorization follow-up",
  "يجب أن يملك حسابك memorization.view أو memorization.manage ضمن المدرسة أو الفرع أو الحلقة.": "Your account needs memorization.view or memorization.manage access for the school, branch, or class.",
  "— الرئيسي": "— Main",
  "لا توجد فروع نشطة ضمن نطاق صلاحية متابعة الحفظ لهذا الحساب.": "There are no active branches within this account’s memorization scope.",
  "لا توجد حلقات نشطة ومصرح بها في الفرع المحدد. المعلم لا يرى إلا حلقاته المعيّنة.": "There are no active authorized classes in the selected branch. Teachers only see their assigned classes.",
  "جارٍ تحميل طلاب الحلقة والمعلمين المعيّنين...": "Loading class students and assigned teachers...",
  "تعذر تحميل بيانات الحلقة": "Could not load class information",
  "تعذر تحميل بيانات الحلقة حاليًا.": "Could not load class information right now.",
  "لا يوجد طلاب في الحلقة": "There are no students in the class",
  "لا يوجد طلاب نشطون مسجلون في الحلقة المحددة حاليًا.": "There are no active students enrolled in the selected class right now.",
  "لا يوجد معلم معيّن للحلقة": "No teacher is assigned to the class",
  "يجب تعيين معلم نشط للحلقة قبل تسجيل متابعة الحفظ.": "Assign an active teacher to the class before recording memorization follow-up.",
  "تعديل سجل المتابعة": "Edit follow-up record",
  "تسجيل متابعة جديدة": "Record new follow-up",
  "تقييم المتابعة": "Follow-up rating",
  "ملخص عام اختياري — ويمكن إدراج عدة ملاحظات مفصلة في سجل الملاحظات أسفل النموذج": "Optional general summary — you can add several detailed notes in the notes history below.",
  "المقدار المطلوب في الحصة القادمة — اختياري": "Required portion for the next session — optional",
  "آخر 20 سجلًا عبر جميع التواريخ.": "Latest 20 records across all dates.",
  "سجلات تاريخ  فقط.": "Records for the selected date only.",
  "عرض تاريخ اليوم": "Show today",
  "عرض كل السجل السابق": "Show all previous records",
  "جارٍ تحميل سجل الحفظ والمراجعة...": "Loading memorization and revision history...",
  "لا توجد سجلات متابعة": "No follow-up records",
  "لم يُسجل لهذا الطالب حفظ أو مراجعة أو اختبار حتى الآن.": "No memorization, revision, or assessment has been recorded for this student yet.",
  "لا توجد سجلات لهذا الطالب في التاريخ المحدد.": "There are no records for this student on the selected date.",
  "معلم الحلقة": "Class teacher",
  "إخفاء التدقيق": "Hide audit trail",
  "سجل التدقيق": "Audit trail",
  "تعديل السجل": "Edit record",
  "توجد تغييرات غير محفوظة.": "There are unsaved changes.",
  "السجل المحمّل لم يتغير.": "The loaded record has not changed.",
  "أدخل بيانات المتابعة ثم احفظ.": "Enter the follow-up information, then save.",

  // Student 360
  "حضور": "Attendance",
  "حفظ ومراجعة": "Memorization and revision",
  "دفعة مالية": "Payment",
  "تعذر العثور على ملف الطالب": "Could not find the student profile",
  "قد لا يكون الطالب موجودًا ضمن مدرستك أو لا تملك صلاحية عرضه.": "The student may not belong to your school, or you may not have permission to view the profile.",
  "تعذر تحميل ملف الطالب": "Could not load the student profile",
  "حدث خطأ أثناء جلب البيانات المسموح بها. يمكنك المحاولة مرة أخرى.": "An error occurred while loading authorized data. You can try again.",
  "ملف الطالب": "Student profile",
  "عرض موحد للبيانات المتاحة حسب صلاحياتك الحالية.": "A unified view of data available under your current permissions.",
  "صورة": "Photo",
  "الفرع غير متاح": "Branch unavailable",
  "· بلا حلقة حالية": "· No current class",
  "لا توجد حلقة معيّنة": "No class assigned",
  "ملخص سريع": "Quick summary",
  "حضور مسجل": "Attendance records",
  "من آخر  سجل": "From the latest records",
  "غياب مسجل": "Recorded absences",
  "سجلات الحفظ والمراجعة": "Memorization and revision records",
  "آخر متابعة:": "Latest follow-up:",
  "لا توجد متابعة مسجلة": "No follow-up recorded",
  "المتبقي المالي": "Outstanding balance",
  "المستحق:": "Due:",
  "لا توجد بيانات ملخصة متاحة": "No summary data available",
  "تظهر الوحدات التي تملك صلاحية عرضها فقط.": "Only modules you are authorized to view are shown.",
  "آخر سجلات الحضور ضمن الحلقة المصرح بها.": "Latest attendance records in the authorized class.",
  "لم يؤثر هذا الخطأ على بقية ملف الطالب.": "This error did not affect the rest of the student profile.",
  "لا توجد سجلات حضور متاحة لهذا الطالب في الوقت الحالي.": "There are no attendance records available for this student right now.",
  "الحفظ والمراجعة": "Memorization and revision",
  "آخر المتابعات ضمن الحلقة المصرح بها.": "Latest follow-ups in the authorized class.",
  "تعذر تحميل الحفظ والمراجعة": "Could not load memorization and revision",
  "لا توجد متابعات حفظ أو مراجعة": "There are no memorization or revision follow-ups",
  "تظهر هنا السجلات عند إضافتها ضمن الحلقة المصرح بها.": "Records appear here when added within the authorized class.",
  "ملخص مالي متاح بحسب صلاحيات المالية الحالية.": "Financial summary available under your current finance permissions.",
  "تعذر تحميل المالية": "Could not load finance data",
  "إجمالي المستحق": "Total due",
  "إجمالي المدفوع": "Total paid",
  "آخر النشاطات": "Latest activity",
  "مجمعة من البيانات المسموح بعرضها في هذا الملف.": "Compiled from data you are authorized to view in this profile.",

  // Student bulk import
  "الاستيراد الجماعي للطلاب": "Bulk student import",
  "ارفع ملف Excel، راجع الأخطاء والتكرارات، ثم اعتمد الصفوف الجاهزة فقط.": "Upload an Excel file, review errors and duplicates, then import only ready rows.",
  "العودة إلى الطلاب": "Back to students",
  "تنزيل نموذج Excel": "Download Excel template",
  "اختيار ملف .xlsx": "Choose .xlsx file",
  "فحص ومعاينة": "Validate and preview",
  "اعتماد الصفوف الجاهزة": "Import ready rows",
  "التراجع عن هذه الدفعة": "Undo this batch",
  "تنزيل تقرير الأخطاء": "Download error report",
  "الإجمالي": "Total",
  "جاهز": "Ready",
  "تحذير": "Warning",
  "مكرر": "Duplicate",
  "خطأ": "Error",
  "تم إنشاؤه": "Created",
  "الصف": "Row",
  "اكتملت المعاينة. لم يتم إنشاء أي طالب بعد.": "Preview complete. No students have been created yet.",
  "تم اعتماد الدفعة وإنشاء الطلاب الجاهزين.": "Batch imported and ready students created.",
  "تم التراجع عن الطلاب الذين أنشأتهم هذه الدفعة.": "Students created by this batch were removed.",
  "تعذر تنفيذ العملية. راجع الملف والصلاحيات ثم أعد المحاولة.": "Could not complete the operation. Review the file and permissions, then try again.",
  "الرفع وحده لا يغيّر بيانات الطلاب. اضغط اعتماد بعد مراجعة الجدول.": "Uploading alone does not change student data. Select Import after reviewing the table.",
  "التراجع يُرفض إذا بدأ استخدام أي طالب مستورد في الحضور أو الحفظ أو المالية أو ربط الأولياء.": "Undo is blocked if an imported student has been used in attendance, memorization, finance, or guardian linking.",
  "رمز الفرع غير موجود": "Branch code does not exist",
  "لا توجد صلاحية على الفرع": "No permission for the branch",
  "رمز الحلقة غير موجود في الفرع": "Class code does not exist in the branch",
  "لم تحدد حلقة": "No class selected",
  "الاسم غير صالح": "Invalid first name",
  "اللقب غير صالح": "Invalid last name",
  "تاريخ الميلاد غير صالح": "Invalid date of birth",
  "تاريخ التسجيل غير صالح": "Invalid registration date",
  "الجنس غير صالح": "Invalid gender",
  "اسم الولي غير صالح": "Invalid guardian name",
  "صلة الولي غير صالحة": "Invalid guardian relationship",
  "هاتف الولي غير صالح": "Invalid guardian phone",
  "طالب مكرر": "Duplicate student",
  "ظهر تكرار قبل الاعتماد": "A duplicate appeared before import",
  "تغيرت صلاحية الفرع": "Branch permission changed",
  "الحلقة لم تعد متاحة": "The class is no longer available",

  // Academic reports
  "الفلتر المختار خارج نطاق صلاحياتك الحالية.": "The selected filter is outside your current permissions.",
  "تحقق من فترة التقرير: يجب أن يكون تاريخ البداية قبل النهاية.": "Check the report period: the start date must be before the end date.",
  "تعذر تحميل بيانات التقرير المفلترة.": "Could not load the filtered report data.",
  "كل الفروع": "All branches",
  "كل الحلقات": "All classes",
  "لا توجد وحدات تعليمية متاحة": "No academic modules are available",
  "يلزم وصول فعلي إلى الحضور أو الحفظ والمراجعة. صلاحيات المالية وحدها لا تفتح هذا المركز.": "You need access to attendance or memorization and revision. Finance permissions alone do not open this center.",
  "صلاحيات التقارير التعليمية": "Academic report permissions",
  "مركز التقارير": "Report center",
  "ملخصات قراءة فقط للحضور والحفظ والحلقات وتحليلات أخطاء التسميع ضمن صلاحياتك الحالية.": "Read-only summaries for attendance, memorization, classes, and recitation-error analysis within your current permissions.",
  "جارٍ التحديث...": "Refreshing...",
  "تطبيق الفلاتر": "Apply filters",
  "سجلات الحضور": "Attendance records",
  "· غائب": "· Absent",
  "متابعات الحفظ": "Memorization follow-ups",
  "الطلاب في النتائج": "Students in results",
  "آخر نشاط": "Latest activity",
  "بعذر": "Excused",
  "الحلقات الظاهرة": "Visible classes",
  "تقرير الحضور": "Attendance report",
  "تقرير الحفظ والمراجعة": "Memorization and revision report",
  "لا توجد بيانات في الفترة": "No data in this period",
  "غيّر الفترة أو الفرع أو الحلقة لعرض النتائج المتاحة.": "Change the period, branch, or class to view available results.",
  "لا توجد سجلات ضمن الفلاتر والفترة المحددة.": "There are no records for the selected filters and period.",
  "لا توجد متابعات حفظ": "No memorization follow-ups",
  "لا توجد متابعات ضمن الفلاتر والفترة المحددة.": "There are no follow-ups for the selected filters and period.",
  "تحليلات متابعة الحفظ": "Memorization follow-up analytics",
  "ملخص حضور الطلاب": "Student attendance summary",
  "عدادات مباشرة دون احتساب نسبة حضور جديدة.": "Live counts without calculating a new attendance rate.",
  "السجلات اليومية": "Daily records",
  "سجلات الحضور حسب التاريخ والفلاتر الحالية.": "Attendance records by date and current filters.",
  "ملخص الحفظ والمراجعة": "Memorization and revision summary",
  "آخر جلسة وقيم التقييم الموجودة دون متوسط مركب.": "Latest session and available ratings without a composite average.",
  "لا توجد حلقات ضمن النطاق والفلاتر الحالية.": "There are no classes within the current scope and filters.",
  "ملخص الحلقات": "Class summary",
  "تجميع مشتق من بيانات الفترة الحالية فقط.": "Summary derived only from the current period’s data.",

  // Financial statements
  "قيد الإقفال": "Closing in progress",
  "رسوم": "Fees",
  "مواد": "Materials",
  "تبرعات": "Donations",
  "منح/إعانات": "Grants / aid",
  "أنشطة": "Activities",
  "تأجير أصول": "Asset rental",
  "رواتب": "Payroll",
  "لوازم": "Supplies",
  "خدمات": "Services",
  "صيانة": "Maintenance",
  "تعذر تحميل القائمة المالية.": "Could not load the financial statement.",
  "لم تبدأ دورة الإقفال": "Closing cycle has not started",
  "الاستحقاقات خلال الشهر": "Charges during the month",
  "المتبقي المستحق بنهاية الشهر": "Outstanding amount at month end",
  "المتأخر بنهاية الشهر": "Overdue amount at month end",
  "التحصيلات خلال الشهر": "Collections during the month",
  "الإيرادات الأخرى": "Other income",
  "الرواتب المستحقة": "Payroll due",
  "الرواتب المدفوعة خلال الشهر": "Payroll paid during the month",
  "رواتب غير مدفوعة عند النهاية": "Unpaid payroll at period end",
  "نتيجة التشغيل": "Operating result",
  "رصيد الخزينة قبل الفترة": "Treasury balance before the period",
  "قيود أرصدة افتتاحية داخل الفترة": "Opening-balance entries within the period",
  "تدفقات داخلة خارجية": "External cash inflows",
  "تدفقات خارجة خارجية": "External cash outflows",
  "صافي النقد الخارجي": "Net external cash flow",
  "الرصيد الختامي": "Closing balance",
  "إيداعات يدوية": "Manual deposits",
  "سحوبات يدوية": "Manual withdrawals",
  "تحويلات داخلية": "Internal transfers",
  "التحصيلات حسب وسيلة الدفع": "Collections by payment method",
  "الاستحقاقات حسب التصنيف": "Charges by category",
  "الإيرادات الأخرى حسب التصنيف": "Other income by category",
  "المصروفات حسب التصنيف": "Expenses by category",

  // Dashboard and attendance
  "معلم": "Teacher",
  "مشرف أكاديمي": "Academic supervisor",
  "مسؤول مالي": "Finance officer",
  "مسؤول التسجيل": "Registration officer",
  "مدير المدرسة": "School manager",
  "تسجيل الحضور": "Record attendance",
  "إدارة حضور طلاب الحلقة اليوم": "Manage today’s class attendance",
  "متابعة الحفظ": "Memorization follow-up",
  "تسجيل إنجاز الطالب ومراجعته": "Record and review student progress",
  "تسجيل طالب جديد في المدرسة": "Register a new student",
  "إنشاء حلقة": "Create class",
  "إضافة حلقة أو مجموعة تعليمية": "Add a class or learning group",
  "إدراج معلم في دليل المدرسة": "Add a teacher to the school directory",
  "إجراء مالي": "Finance action",
  "تسجيل دفعة أو مراجعة الحسابات": "Record a payment or review accounts",
  "مرحبًا،": "Welcome,",
  "مرحبًا بك": "Welcome",
  "نظرة سريعة على ما يحتاج اهتمامك اليوم.": "A quick view of what needs your attention today.",
  "ملخص المدرسة": "School summary",
  "بيانات متاحة ضمن نطاقك الحالي.": "Data available within your current scope.",
  "إجمالي الطلاب": "Total students",
  "الحلقات النشطة": "Active classes",
  "إجراءات سريعة": "Quick actions",
  "اختصارات تناسب صلاحياتك.": "Shortcuts based on your permissions.",
  "أحدث الحلقات المسجلة في المدرسة.": "Latest classes registered in the school.",
  "لا توجد حلقات نشطة بعد": "No active classes yet",
  "ستظهر الحلقات هنا فور إضافتها إلى المدرسة.": "Classes will appear here as soon as they are added.",
  "فرع غير محدد": "Branch not specified",
  "البدء السريع": "Quick start",
  "انتقل مباشرة إلى وحدة عملك.": "Go directly to your workspace.",
  "الحضور والغياب": "Attendance and absence",
  "لا توجد اختصارات إضافية": "No additional shortcuts",
  "استخدم قائمة المزيد للوصول إلى الوحدات المتاحة لك.": "Use the More menu to access your available modules.",
  "مبرر": "Excused",
  "تم حفظ حضور  طالب بنجاح.": "Attendance saved successfully.",
  "تعذر تسجيل الخروج حاليًا.": "Could not sign out right now.",
  "جارٍ تحميل نطاق الحضور...": "Loading attendance scope...",
  "تعذر تحميل الحضور": "Could not load attendance",
  "تعذر التحقق من صلاحيات الحضور حاليًا.": "Could not verify attendance permissions right now.",
  "لا توجد صلاحية لعرض الحضور": "You do not have permission to view attendance",
  "يجب أن يملك حسابك attendance.view أو attendance.manage ضمن المدرسة أو الفرع.": "Your account needs attendance.view or attendance.manage access for the school or branch.",
  "العودة إلى لوحة التحكم": "Back to dashboard",
  "لا توجد فروع نشطة ضمن نطاق صلاحية الحضور لهذا الحساب.": "There are no active branches within this account’s attendance scope.",
  "ملخص الحضور": "Attendance summary",
  "الحاضرون": "Present",
  "الغائبون": "Absent",
  "المتأخرون": "Late",
  "تم تحميل جلسة مسجلة لهذا التاريخ.": "A recorded session was loaded for this date.",
  "لا توجد جلسة سابقة؛ ستُنشأ عند أول حفظ.": "There is no previous session; one will be created on the first save.",
  "جارٍ تحميل طلاب الحلقة وسجل الحضور...": "Loading class students and attendance history...",
  "طلاب الحلقة": "Class students",
  "لم تُحدّد الحالة": "Status not selected",
  "حالة": "Status",
  "غير مسجلة": "Not recorded",
  "— الوصول": "— Arrival",
  "حدّد حالة جميع الطلاب قبل الحفظ.": "Select a status for every student before saving.",
  "السجل محفوظ.": "Record saved.",
  "إنشاء وحفظ": "Create and save",

  // Finance reports and period close
  "رواتب قديمة/مصروفات أجور": "Legacy payroll / wage expenses",
  "الإيجار": "Rent",
  "الخدمات": "Services",
  "الصيانة": "Maintenance",
  "اللوازم": "Supplies",
  "النقل": "Transport",
  "الأنشطة": "Activities",
  "مستوى المدرسة": "School level",
  "فرع غير متاح": "Branch unavailable",
  "التحصيلات": "Collections",
  "المتأخرات": "Overdue balances",
  "التدفق المالي": "Cash flow",
  "العودة إلى المالية": "Back to finance",
  "الاستحقاقات المحتسبة": "Calculated charges",
  "التحصيلات المكتملة": "Completed collections",
  "الرواتب المدفوعة": "Payroll paid",
  "المصروفات التشغيلية": "Operating expenses",
  "إجمالي التدفقات الخارجة": "Total outflows",
  "صافي التدفق": "Net cash flow",
  "حالة الاستحقاق": "Charge status",
  "تصنيف المصروف": "Expense category",
  "مسجل": "Recorded",
  "إجمالي الخروج": "Total outflow",
  "حسب الشهر": "By month",
  "الشهر": "Month",
  "ممنوع": "Restricted",
  "إنشاء الفترة": "Create period",
  "بدء الإقفال": "Start closing",
  "إغلاق الفترة": "Close period",
  "إعادة فتح": "Reopen",
  "الرصيد الفعلي للحساب «» بالدينار:": "Actual account balance in DZD:",
  "أدخل رصيدًا رقميًا صحيحًا.": "Enter a valid numeric balance.",
  "تاريخ العد النقدي أو كشف الحساب (YYYY-MM-DD):": "Cash count or statement date (YYYY-MM-DD):",
  "تاريخ العد أو كشف الحساب مطلوب.": "Cash count or statement date is required.",
  "مرجع كشف البنك:": "Bank statement reference:",
  "مرجع كشف الحساب البريدي:": "Postal account statement reference:",
  "مرجع كشف الحساب مطلوب.": "Statement reference is required.",
  "ملاحظة المطابقة (اختيارية):": "Reconciliation note (optional):",
  "تم حفظ مطابقة جديدة دون الكتابة فوق السجل السابق.": "A new reconciliation was saved without overwriting the previous record.",
  "مفتوحة ضمنيًا — لم تبدأ دورة الإقفال": "Open by default — closing cycle has not started",
  "بدأت مرحلة الإقفال وأصبحت العمليات المؤرخة داخل الشهر محمية.": "Closing has started and transactions dated within the month are now protected.",
  "أغلقت الفترة المالية بعد اكتمال المطابقة.": "The financial period was closed after reconciliation was completed.",
  "سبب إعادة فتح الفترة للتصحيح (يسجل في سجل التدقيق):": "Reason for reopening the period (recorded in the audit trail):",
  "أعيد فتح الفترة للتصحيح المدقق.": "The period was reopened for audited correction.",
  "صندوق نقدي": "Cash box",
  "حساب بنكي": "Bank account",
  "حساب بريدي": "Postal account",
  "مطابق": "Reconciled",
  "يوجد فرق": "Difference found",
  "غير مطابق": "Not reconciled",

  // Charges, teachers, treasury, and staff
  "لا تملك صلاحية الإدارة في فرع هذا الطالب.": "You do not have management permission for this student’s branch.",
  "خطة الرسوم غير متاحة لفرع الطالب.": "The fee plan is not available for the student’s branch.",
  "تم تحديث الاستحقاق.": "Charge updated.",
  "تم إنشاء الاستحقاق.": "Charge created.",
  "تم إلغاء الاستحقاق دون حذفه.": "Charge cancelled without deleting its history.",
  "خطط الرسوم": "Fee plans",
  "البحث بالطالب أو الخطة أو الملاحظات...": "Search by student, plan, or notes...",
  "تصفية حسب خطة الرسوم": "Filter by fee plan",
  "طالب غير متاح": "Student unavailable",
  "بدون خطة": "No plan",
  "إغلاق القائمة": "Close menu",
  "تبديل القائمة": "Toggle menu",
  "تعديل الاستحقاق": "Edit charge",
  "إنشاء استحقاق جديد": "Create new charge",
  "بدون خصم": "No discount",
  "مبلغ ثابت": "Fixed amount",
  "نسبة مئوية": "Percentage",
  "قيمة الخصم (دج)": "Discount amount (DZD)",
  "نسبة الخصم (%)": "Discount percentage (%)",
  "مثال: خصم الإخوة": "Example: sibling discount",
  "وصف مختصر للاستحقاق": "Short charge description",
  "إنشاء الاستحقاق": "Create charge",
  "إضافة معلم جديد": "Add new teacher",
  "أدخل بيانات المعلم واربطه بأحد فروع المدرسة.": "Enter the teacher’s information and link them to a school branch.",
  "تُحفظ المسودة تلقائيًا في هذا التبويب حتى تحفظها أو تلغيها.": "The draft is saved automatically in this tab until you save or cancel it.",
  "تم استرجاع المسودة غير المحفوظة.": "Unsaved draft restored.",
  "مثال: محمد": "Example: Mohammed",
  "مثال: بن سالم": "Example: Ben Salem",
  "اختر الجنس": "Choose gender",
  "مثال: 0550000000": "Example: 0550000000",
  "مثال: تحفيظ القرآن": "Example: Quran memorization",
  "المؤهل العلمي": "Qualification",
  "مثال: إجازة في القرآن الكريم": "Example: Quran certification",
  "أي معلومات إضافية مفيدة...": "Any useful additional information...",
  "تعذر تحميل فروع المدرسة حاليًا.": "Could not load school branches right now.",
  "الفرع مطلوب.": "Branch is required.",
  "الاسم مطلوب.": "First name is required.",
  "يجب أن يتراوح الاسم بين حرفين و100 حرف.": "First name must be between 2 and 100 characters.",
  "اللقب مطلوب.": "Last name is required.",
  "يجب أن يتراوح اللقب بين حرفين و100 حرف.": "Last name must be between 2 and 100 characters.",
  "الجنس مطلوب.": "Gender is required.",
  "أدخل بريدًا إلكترونيًا صحيحًا.": "Enter a valid email address.",
  "تاريخ التوظيف مطلوب.": "Employment date is required.",
  "تمت إضافة المعلم بنجاح": "Teacher added successfully",
  "عرض الخزينة": "View treasury",
  "فرع": "Branch",
  "تم إيقاف الحساب مع حفظ تاريخه.": "Account deactivated while preserving its history.",
  "تم تفعيل الحساب.": "Account activated.",
  "إيقاف": "Deactivate",
  "تفعيل": "Activate",
  "تمت أرشفة الحساب.": "Account archived.",
  "حساب": "Account",
  "سبب عكس الإيراد (يحفظ في السجل):": "Reason for reversing income (saved in history):",
  "تم عكس الإيراد وحركة الخزينة.": "Income and treasury transaction reversed.",
  "سبب عكس الحركة:": "Reason for reversing transaction:",
  "تم عكس الحركة.": "Transaction reversed.",
  "سبب عكس التحويل:": "Reason for reversing transfer:",
  "تم عكس طرفي التحويل.": "Both sides of the transfer were reversed.",
  "تم إنشاء الحساب وتسجيل رصيده الافتتاحي.": "Account created and opening balance recorded.",
  "تم تسجيل الإيراد وحركة الخزينة.": "Income and treasury transaction recorded.",
  "تم التحويل بين الحسابين بصورة متوازنة.": "Balanced transfer completed between the two accounts.",
  "تم تسجيل حركة الخزينة.": "Treasury transaction recorded.",
  "ملاحظات اختيارية": "Optional notes",
  "مرجع اختياري": "Optional reference",
  "سبب الحركة (مطلوب)": "Transaction reason (required)",
  "تعذر تحميل الموظفين.": "Could not load employees.",
  "أدخل اسم الموظف ووظيفته بصورة صحيحة.": "Enter a valid employee name and job title.",
  "تعذر حفظ الموظف. تحقق من الرقم الوظيفي والبيانات.": "Could not save the employee. Check the employee number and information.",
  "تعذر تغيير حالة الموظف.": "Could not change the employee status.",
  "الإدارة": "Management",
  "الموظفون والرواتب": "Employees and payroll",
  "أنشئ سجل الموظف دون إنشاء حساب دخول. الرواتب متصلة بالمالية محاسبيًا.": "Create an employee record without a sign-in account. Payroll is connected to finance accounting.",
  "البحث": "Search",
  "الاسم، الوظيفة، الرقم أو الهاتف": "Name, job, number, or phone",
  "تعديل الموظف": "Edit employee",
  "إضافة موظف": "Add employee",
  "موظف جديد": "New employee",
  "الوظيفة": "Job",
  "مسمى آخر": "Other title",
  "الرقم الوظيفي": "Employee number",
  "جارٍ تحميل الموظفين...": "Loading employees...",
  "لا يوجد موظفون في هذا النطاق.": "There are no employees in this scope.",
  "دون رقم وظيفي": "No employee number",
  "دون هاتف": "No phone",
  "تعطيل": "Deactivate",
  "الوظيفة تصف عمل الموظف فقط ولا تمنحه صلاحيات في النظام.": "The job title describes the employee’s work only and does not grant system permissions.",

  // Guardian portal and analytics
  "الأب": "Father",
  "الأم": "Mother",
  "الولي القانوني": "Legal guardian",
  "قريب": "Relative",
  "ولي أمر": "Guardian",
  "تنبيهات الغياب مفعّلة على هذا الجهاز": "Absence alerts are enabled on this device",
  "سيصبح هذا الجهاز جاهزًا لاستقبال تنبيهات الحضور عند تفعيل الإرسال من المدرسة.": "This device will be ready to receive attendance alerts when the school enables sending.",
  "الإشعارات محظورة في المتصفح": "Notifications are blocked in the browser",
  "يمكنك السماح بإشعارات QuranOS من إعدادات الموقع في المتصفح ثم المحاولة مجددًا.": "Allow QuranOS notifications in the browser’s site settings, then try again.",
  "هذا المتصفح لا يدعم Push": "This browser does not support push notifications",
  "استخدم تطبيق QuranOS المثبّت أو متصفحًا حديثًا يدعم إشعارات الويب.": "Use the installed QuranOS app or a modern browser that supports web notifications.",
  "جارٍ فحص جاهزية الإشعارات": "Checking notification readiness",
  "لن يطلب QuranOS إذن الإشعارات إلا عندما تضغط زر التفعيل بنفسك.": "QuranOS will request notification permission only when you select Enable.",
  "تنبيهات غياب الأبناء": "Children’s absence alerts",
  "فعّل الإشعارات على هذا الجهاز حتى يصبح جاهزًا لتنبيهك عند اعتماد غياب أحد الأبناء.": "Enable notifications on this device to receive an alert when a child’s absence is confirmed.",
  "تعذر تفعيل الإشعارات على هذا الجهاز حاليًا. حاول مرة أخرى.": "Could not enable notifications on this device right now. Try again.",
  "تعذر إيقاف الإشعارات على هذا الجهاز حاليًا. حاول مرة أخرى.": "Could not disable notifications on this device right now. Try again.",
  "جارٍ التفعيل...": "Enabling...",
  "تفعيل تنبيهات الغياب": "Enable absence alerts",
  "جارٍ الإيقاف...": "Disabling...",
  "إيقافها على هذا الجهاز": "Disable on this device",
  "· ولي أساسي": "· Primary guardian",
  "غير مسند إلى حلقة حاليًا": "Not assigned to a class right now",
  "سورة رقم": "Surah number",
  "تعذر تحميل تحليلات المتابعة ضمن نطاقك الحالي. لم تُجرَ أي تغييرات.": "Could not load follow-up analytics within your current scope. No changes were made.",
  "فلاتر أخطاء الحفظ": "Memorization error filters",
  "هذه الفلاتر تخص ملاحظات المتابعة فقط، بينما تبقى فترة التقرير والفرع والحلقة والطالب من الفلاتر العامة أعلاه.": "These filters apply only to follow-up notes; the report period, branch, class, and student use the general filters above.",
  "لا توجد ملاحظات متابعة ضمن الفلاتر": "No follow-up notes match the filters",
  "غيّر الفترة أو نطاق الحلقة أو فلاتر النوع والحالة والأولوية.": "Change the period, class scope, or type, status, and priority filters.",
  "ملاحظات المتابعة": "Follow-up notes",
  "لـ": "For",
  "طالب": "Student",
  "· تحسنت": "· Improved",
  "مواضع متكررة": "Repeated locations",
  "عالية الأولوية": "High priority",
  "أكثر أنواع الأخطاء": "Most common error types",
  "تجميع مشتق من الملاحظات الواقعة ضمن الفترة والفلاتر الحالية.": "Summary derived from notes within the current period and filters.",
  "المواضع الأكثر تكرارًا": "Most repeated locations",
  "السورة ونطاق الآيات التي ظهرت فيها الملاحظة أكثر من غيرها.": "Surahs and verse ranges where notes appeared most often.",
  "الطلاب الأعلى حاجة للمتابعة": "Students needing the most follow-up",
  "ترتيب قراءة فقط حسب الملاحظات غير المعالجة والتكرار، ضمن صلاحياتك الحالية.": "Read-only ranking by unresolved notes and repetition within your current permissions.",
  "اتجاه التحسن": "Improvement trend",
  "حركات الحالة الموثقة في سجل التدقيق خلال الفترة المحددة.": "Status changes recorded in the audit trail during the selected period.",
  "أولوية المتابعة الآن": "Current follow-up priority",
  "أحدث الملاحظات عالية الأولوية التي لم تُحل بعد.": "Latest high-priority notes that remain unresolved.",

  // Roster, receipts, recurring billing, guardian student view
  "معلم أساسي": "Primary teacher",
  "معلم مساعد": "Assistant teacher",
  "تم ربط الطالب بالحلقة.": "Student linked to the class.",
  "تمت إزالة تعيين الحلقة عن الطالب.": "Student’s class assignment removed.",
  "جارٍ تحميل الطلاب والحلقات...": "Loading students and classes...",
  "لا يوجد طلاب نشطون داخل الفروع التي تملك صلاحية إدارتها.": "There are no active students in branches you can manage.",
  "لا يمكن تعديل هذا التعيين لأن المعلم غير نشط حاليًا.": "This assignment cannot be edited because the teacher is inactive.",
  "تم حفظ تعيين المعلم للحلقة.": "Teacher assignment saved.",
  "تم إلغاء التعيين دون حذف السجل.": "Assignment cancelled without deleting its history.",
  "تعديل الدور": "Edit role",
  "إعادة تفعيل": "Reactivate",
  "جارٍ الإلغاء...": "Cancelling...",
  "إلغاء التعيين": "Cancel assignment",
  "لا توجد حلقات نشطة داخل الفروع التي تملك صلاحية إدارتها.": "There are no active classes in branches you can manage.",
  "جارٍ تحميل المعلمين والتعيينات...": "Loading teachers and assignments...",
  "لا توجد تعيينات نشطة لهذه الحلقة.": "There are no active assignments for this class.",
  "إدارة ربط الطلاب بالحلقات": "Manage student-class links",
  "إدارة تعيين المعلمين للحلقات": "Manage class teacher assignments",
  "ربط الطلاب بالحلقات": "Link students to classes",
  "تعيين معلمي الحلقات": "Assign class teachers",
  "الوصولات الرسمية": "Official receipts",
  "إصدار وإعادة طباعة وصولات التسجيل والدفع دون تغيير رقم الوصل الأصلي.": "Issue and reprint registration and payment receipts without changing the original receipt number.",
  "جارٍ تحميل الوصولات...": "Loading receipts...",
  "تعذر تحميل مركز الوصولات حاليًا.": "Could not load the receipt center right now.",
  "لا تملك صلاحية الوصول إلى الوصولات الرسمية.": "You do not have permission to access official receipts.",
  "إصدار وصل دفع": "Issue payment receipt",
  "اختر دفعة مسجلة. إذا كان لها وصل سابق فسيُعاد نفس الوصل ونفس الرقم.": "Choose a recorded payment. If it already has a receipt, the same receipt and number will be reused.",
  "اختر الدفعة": "Choose payment",
  "إصدار وصل الدفع": "Issue payment receipt",
  "تم تجهيز وصل الدفع الرسمي.": "Official payment receipt prepared.",
  "إصدار وصل تسجيل": "Issue registration receipt",
  "يُصدر مرة واحدة لتاريخ التسجيل الحالي، وإعادة الإصدار تعيد نفس الوصل.": "Issued once for the current registration date; reissuing returns the same receipt.",
  "إصدار وصل التسجيل": "Issue registration receipt",
  "جارٍ الإصدار...": "Issuing...",
  "تم تجهيز وصل التسجيل الرسمي.": "Official registration receipt prepared.",
  "بحث برقم الوصل أو اسم الطالب أو الفرع...": "Search by receipt number, student, or branch...",
  "كل الوصولات": "All receipts",
  "دفع": "Payment",
  "الإجراء": "Action",
  "عرض / طباعة": "View / print",
  "لا توجد وصولات رسمية مطابقة بعد.": "No matching official receipts yet.",
  "دون مبلغ": "No amount",
  "شهري": "Monthly",
  "ربع سنوي": "Quarterly",
  "سنوي": "Annual",
  "تم إنشاء  استحقاقًا دوريًا.": "Recurring charges created.",
  "عدد أيام التذكير يجب أن يكون بين 1 و30.": "Reminder days must be between 1 and 30.",
  "تم إنشاء  تذكيرًا جديدًا.": "New reminders created.",
  "فرع الخطة": "Plan branch",
  "يوم الاستحقاق:": "Due day:",
  "يجب تحديد يوم الاستحقاق في الخطة": "A due day must be set in the plan",
  "طلاب مؤهلون": "Eligible students",
  "موجود مسبقًا": "Already exists",
  "سيُنشأ": "Will be created",
  "قبل الخصم": "Before discount",
  "توفير الخصومات": "Discount savings",
  "استحقاقات قريبة": "Upcoming charges",
  "استحقاقات متأخرة": "Overdue charges",
  "تذكيرات قريبة جديدة": "New upcoming reminders",
  "تذكيرات تأخير جديدة": "New overdue reminders",
  "حفظ جديد": "New memorization",
  "تقييم": "Rating",
  "سورة": "Surah",
  "مستحق": "Due",
  "تحويل بريدي": "Postal transfer",
  "طريقة أخرى": "Other method",
  "نسبة الحضور": "Attendance rate",
  "الحاضر والمتأخر من السجلات المسجلة": "Present and late among recorded entries",
  "عدد المتابعات": "Follow-up count",
  "متوسط التقييم": "Average rating",
  "مجموع الأخطاء": "Total errors",
  "آخر متابعة": "Latest follow-up",
  "إجمالي الرسوم": "Total fees",
  "المتأخر": "Overdue",
  "مبالغ تجاوز تاريخ استحقاقها": "Amounts past their due date",
  "لا توجد متأخرات": "No overdue amounts",

  // Expenses, fee plans, payments, payroll, and reconciliation
  "لا تملك صلاحية إدارة المصروف في هذا النطاق.": "You do not have permission to manage expenses in this scope.",
  "تم تعديل المصروف المسجل.": "Recorded expense updated.",
  "تم تسجيل المصروف.": "Expense recorded.",
  "هل تريد إلغاء المصروف \"\"؟ سيبقى القيد محفوظًا ولن يمكن إعادته من الواجهة.": "Cancel this expense? The entry will remain in history and cannot be restored from the interface.",
  "تم إلغاء المصروف مع حفظ السجل المحاسبي.": "Expense cancelled and accounting history preserved.",
  "الوصف، المرجع، الملاحظات...": "Description, reference, notes...",
  "تصفية حسب التصنيف": "Filter by category",
  "تصفية حسب طريقة الدفع": "Filter by payment method",
  "المدرسة وجميع الفروع المتاحة": "School and all available branches",
  "تعديل المصروف المسجل": "Edit recorded expense",
  "إضافة مصروف جديد": "Add new expense",
  "تسجيل المصروف": "Record expense",
  "عامة": "School-wide",
  "لا تملك صلاحية إدارة الخطط في هذا النطاق.": "You do not have permission to manage plans in this scope.",
  "تم تحديث خطة الرسوم.": "Fee plan updated.",
  "تمت إضافة خطة الرسوم.": "Fee plan added.",
  "هل تريد أرشفة خطة «»؟ لن تُحذف الخطة ويمكن الرجوع إليها في السجل.": "Archive this plan? It will remain available in history.",
  "تمت أرشفة خطة الرسوم.": "Fee plan archived.",
  "البحث بالاسم أو الرمز أو الوصف...": "Search by name, code, or description...",
  "تصفية حسب دورة الفوترة": "Filter by billing cycle",
  "لا يوجد وصف": "No description",
  "عامة للمدرسة": "School-wide",
  "تعديل خطة الرسوم": "Edit fee plan",
  "إضافة خطة رسوم": "Add fee plan",
  "مثال: الرسوم الشهرية": "Example: monthly fees",
  "تفاصيل موجزة عن الخطة...": "Brief plan details...",
  "حفظ الخطة": "Save plan",
  "لا تملك صلاحية تسجيل دفعة في هذا الفرع.": "You do not have permission to record a payment in this branch.",
  "تم تسجيل السداد الكامل.": "Full payment recorded.",
  "تم تسجيل الدفعة الجزئية.": "Partial payment recorded.",
  "هل تريد عكس الدفعة بمبلغ ؟ سيبقى القيد محفوظًا ولن يُحذف.": "Reverse this payment? The entry will remain in history.",
  "تم عكس الدفعة وتحديث حالة الاستحقاق.": "Payment reversed and charge status updated.",
  "طالب، استحقاق، مرجع...": "Student, charge, reference...",
  "من تاريخ": "From date",
  "إلى تاريخ": "To date",
  "استحقاق غير متاح": "Charge unavailable",
  "لا توجد ملاحظات": "No notes",
  "لا توجد استحقاقات مفتوحة قابلة للدفع": "There are no open payable charges",
  "تعذر تنفيذ العملية. تحقق من الحالة والصلاحيات والبيانات المدخلة.": "Could not complete the operation. Check the status, permissions, and entered data.",
  "اختر الموظف وأدخل راتبًا صحيحًا.": "Choose an employee and enter a valid salary.",
  "تم حفظ إعداد الراتب مع تاريخ سريانه.": "Salary setup saved with its effective date.",
  "تم تحديث زيادات وخصومات الراتب.": "Salary additions and deductions updated.",
  "لم يُنشأ": "Not created",
  "تم إنشاء مسير الشهر دون تكرار البنود.": "Monthly payroll run created without duplicate items.",
  "عدد البنود": "Item count",
  "صافي المسير": "Payroll net",
  "تم إنهاء سريان إعداد الراتب مع حفظ التاريخ.": "Salary setup ended while preserving its history.",
  "تم اعتماد المسير وأصبح جاهزًا للدفع.": "Payroll run approved and ready for payment.",
  "تم إلغاء المسير مع حفظ أثره.": "Payroll run cancelled with its audit history preserved.",
  "تم إغلاق المسير بعد تسوية البنود.": "Payroll run closed after settling its items.",
  "يُستخدم فقط عند العكس": "Used only for reversals",
  "إداري/موظف": "Administrator / employee",
  "تم تسجيل دفع الراتب.": "Salary payment recorded.",
  "تم إلغاء بند الراتب.": "Payroll item cancelled.",
  "تم عكس دفعة الراتب مع حفظ السجل.": "Salary payment reversed with history preserved.",
  "لا يوجد حساب خزينة قابل للربط في نطاق هذه العملية.": "No treasury account can be linked within this operation’s scope.",
  "تم ربط  بحساب .": "Transaction linked to the account.",
  "التدفقات الداخلة التجارية": "Operational inflows",
  "التدفقات الخارجة التجارية": "Operational outflows",
  "الصافي التجاري": "Operational net",
  "الصافي المرتبط بالخزينة": "Treasury-linked net",
  "الخزينة مطابقة للعمليات المربوطة": "Treasury matches linked transactions",
  "يوجد  عملية غير مربوطة": "There are unlinked transactions",
  "دفعات الطلاب": "Student payments",
  "إيرادات أخرى": "Other income",
  "دخول": "Inflow",
  "خروج": "Outflow",
  "جارٍ الربط": "Linking",
  "ربط": "Link",

  // Memorization notes and official receipts
  "تمت إضافة الملاحظة إلى جلسة التسميع. يمكنك إدراج ملاحظة أخرى الآن.": "Note added to the recitation session. You can add another note now.",
  "تمت إضافة نقطة المتابعة. ستظهر تلقائيًا في الحصة القادمة ما دامت تحتاج متابعة.": "Follow-up point added. It will appear automatically in the next session while it still needs attention.",
  "توجد نسخة أحدث من المنصة. أعد تحميل الصفحة قبل إضافة الملاحظة.": "A newer platform version is available. Reload before adding the note.",
  "تم حفظ أن هذه النقطة تمت معالجتها.": "This point was marked as resolved.",
  "تم تسجيل التحسن مع إبقاء النقطة تحت المراقبة.": "Improvement recorded while keeping the point under observation.",
  "أعيدت النقطة إلى قائمة التركيز.": "The point was returned to the focus list.",
  "توجد نسخة أحدث من المنصة. أعد تحميل الصفحة قبل تحديث الحالة.": "A newer platform version is available. Reload before updating the status.",
  "نقاط تحتاج تركيزًا اليوم": "Points needing attention today",
  "إخفاء سجل الملاحظات": "Hide notes history",
  "إغلاق الإدراج": "Close entry",
  "إضافة ملاحظة إلى جلسة التسميع": "Add note to recitation session",
  "ملاحظة متابعة جديدة": "New follow-up note",
  "مثال: يتردد في بداية الآية ويخلط بينها وبين الموضع المشابه...": "Example: Hesitates at the beginning of the verse and confuses it with a similar passage...",
  "سترتبط الملاحظة بسجل التسميع الحالي. الملاحظات المدرجة:": "The note will be linked to the current recitation record. Notes added:",
  "يمكن إضافة الملاحظة مستقلة عن سجل جلسة محدد.": "The note can be added independently of a specific session record.",
  "حفظ وإضافة ملاحظة أخرى": "Save and add another note",
  "رسوم دراسية": "Tuition fees",
  "رسوم تسجيل": "Registration fees",
  "وصل دفع رسمي": "Official payment receipt",
  "وصل تسجيل رسمي": "Official registration receipt",
  "طباعة / حفظ PDF": "Print / save PDF",
  "البيان": "Description",
  "المبلغ بالحروف": "Amount in words",
  "تاريخ الدفع": "Payment date",
  "المرجع": "Reference",
  "استلم / أصدر بواسطة": "Received / issued by",
  "حالة الوصل": "Receipt status",
  "معكوس / ملغى محاسبيًا": "Reversed / cancelled in accounting",
  "هذا الوصل مرتبط بدفعة تم عكسها محاسبيًا. يبقى محفوظًا لأغراض التدقيق ولا يُعد إثباتًا لسداد قائم.": "This receipt is linked to a payment reversed in accounting. It is retained for audit purposes and is not proof of an active payment.",
  "إثبات تسجيل — دون مبلغ مالي": "Registration proof — no financial amount",
  "إثبات تسجيل الطالب بالمدرسة": "Proof of student registration at the school",
  "نسخة رسمية من QuranOS": "Official QuranOS copy",

  // Classes and notifications
  "إضافة حلقة جديدة": "Add new class",
  "أدخل بيانات الحلقة وربطها بأحد فروع المدرسة.": "Enter the class information and link it to a school branch.",
  "اسم الحلقة": "Class name",
  "مثال: حلقة الفجر": "Example: Fajr class",
  "رمز الحلقة": "Class code",
  "مثال: FAJR_01": "Example: FAJR_01",
  "أحرف إنجليزية كبيرة وأرقام وشرطة سفلية (_) فقط.": "Uppercase English letters, numbers, and underscores (_) only.",
  "مثال: 05:30 - 06:30": "Example: 05:30 - 06:30",
  "اسم الحلقة مطلوب.": "Class name is required.",
  "يجب أن يتراوح اسم الحلقة بين حرفين و150 حرفًا.": "Class name must be between 2 and 150 characters.",
  "رمز الحلقة مطلوب.": "Class code is required.",
  "استخدم أحرفًا إنجليزية كبيرة وأرقامًا وشرطة سفلية فقط.": "Use uppercase English letters, numbers, and underscores only.",
  "تمت إضافة الحلقة بنجاح": "Class added successfully",
  "التعليم والحفظ": "Learning and memorization",
  "النظام": "System",
  "أولياء الطلاب": "Student guardians",
  "تعذر تحميل المستلمين.": "Could not load recipients.",
  "أضف العنوان والنص وحدد مستلمًا واحدًا على الأقل.": "Add a title and message, then select at least one recipient.",
  "تم إرسال الإشعار إلى  مستلمًا.": "Notification sent to the selected recipients.",
  "تعذر إرسال الإشعار.": "Could not send the notification.",
  "أرسل إشعارًا فرديًا إلى إدارة المدرسة أو معلمي أبنائك.": "Send an individual notification to school management or your children’s teachers.",
  "اختر إرسالًا فرديًا أو جماعيًا أو أشخاصًا محددين، وراجع العدد قبل الإرسال.": "Choose individual, group, or specific recipients and review the count before sending.",
  "ابحث باسم الموظف أو الولي أو الطالب": "Search by employee, guardian, or student",
  "جارٍ تحميل المستلمين...": "Loading recipients...",
  "لا يوجد مستلمون مطابقون.": "No matching recipients.",
  "رابط داخلي (اختياري)": "Internal link (optional)",
  "عدد المستلمين قبل الإرسال": "Recipient count before sending",
  "سجل موحد للإشعارات الواردة والمرسلة من وحدات QuranOS.": "A unified history of received and sent notifications across QuranOS modules.",
  "تعذر تحميل الإشعارات. أعد المحاولة.": "Could not load notifications. Try again.",
  "جارٍ تحميل الإشعارات...": "Loading notifications...",
  "لا توجد إشعارات في هذا القسم بعد.": "There are no notifications in this section yet.",
  "غير مقروء": "Unread",
  "يمكن لولي الأمر إرسال إشعار فردي فقط إلى إدارة المدرسة أو معلمي أبنائه.": "A guardian can send individual notifications only to school management or their children’s teachers.",

  // Discounts, finance home, authentication, and navigation
  "اختر الطالب أولًا.": "Choose a student first.",
  "قيمة الخصم غير صالحة.": "Invalid discount value.",
  "اكتب سببًا واضحًا للخصم.": "Enter a clear reason for the discount.",
  "تحقق من مدة الخصم.": "Check the discount period.",
  "تم حفظ سياسة الخصم وستظهر في معاينة الاشتراك الدوري.": "Discount policy saved and will appear in the recurring billing preview.",
  "السياسة لم تعد نشطة أو غير متاحة.": "The policy is no longer active or available.",
  "تم إيقاف سياسة الخصم مع الاحتفاظ بتاريخها.": "Discount policy deactivated with its history preserved.",
  "مثال: 20": "Example: 20",
  "مثال: 500": "Example: 500",
  "مثال: تخفيض اجتماعي معتمد للسنة الدراسية الحالية": "Example: approved social discount for the current school year",
  "طالب غير نشط/غير ظاهر": "Inactive / unavailable student",
  "مستمر": "Ongoing",
  "· يطبق على الدوري": "· Applies to recurring billing",
  "· مراجعة يدوية": "· Manual review",
  "الرسوم المستحقة": "Fees due",
  "استحقاق": "Charge",
  "المبالغ المحصلة": "Collected amounts",
  "دفعة": "Payment",
  "بعد خصم الدفعات المكتملة": "After completed payments",
  "مصروف": "Expense",
  "جارٍ تحميل ملخص المالية": "Loading finance summary",
  "صلاحية الإدارة المالية متاحة": "Finance management access available",
  "عرض المالية": "View finance",
  "إدارة المصروفات فقط": "Expense management only",
  "إدارة مالية": "Finance management",
  "تعذر تسجيل الدخول. تحقق من البريد الإلكتروني وكلمة المرور.": "Could not sign in. Check your email and password.",
  "تعذر تسجيل الدخول حاليًا. حاول مرة أخرى لاحقًا.": "Could not sign in right now. Try again later.",
  "منظومة إدارة المدارس القرآنية": "Quran School Management System",
  "تنظيم • تعليم • متابعة • إتقان": "Organize • Teach • Follow up • Excel",
  "كلمة المرور": "Password",
  "نسيت كلمة المرور؟": "Forgot password?",
  "جارٍ تسجيل الدخول...": "Signing in...",
  "تثبيت QuranOS على الهاتف": "Install QuranOS on your phone",
  "جارٍ فتح التثبيت...": "Opening installer...",
  "يفتح كتطبيق مستقل من الشاشة الرئيسية.": "Opens as a standalone app from your home screen.",
  "الملخص": "Summary",
  "الدفعات": "Payments",
  "المطابقة": "Reconciliation",
  "إقفال الفترة": "Period close",
  "القوائم المالية": "Financial statements",
  "جارٍ تحميل التنقل المالي": "Loading finance navigation",
  "التنقل المالي": "Finance navigation",
  "إضافة حلقة": "Add class",
  "البحث باسم الحلقة أو رمزها...": "Search by class name or code...",
  "التوقيت": "Schedule",
  "تعذر تحميل قائمة الحلقات حاليًا.": "Could not load the class list right now.",
  "لم تتم إضافة أي حلقة بعد.": "No classes have been added yet.",
  "عدد السجلات": "Record count",
  "المدفوع المكتمل": "Completed payments",
  "دفعات معكوسة محفوظة": "Preserved reversed payments",
  "موظف": "Employee",
  "لم يُسجل دفع": "No payment recorded",
  "استيراد Excel": "Import Excel",
  "البحث بالاسم أو الهاتف أو البريد...": "Search by name, phone, or email...",
  "جميع الحلقات": "All classes",
  "جارٍ تحميل قائمة الطلاب...": "Loading students...",
  "تعذر تحميل قائمة الطلاب حاليًا.": "Could not load the student list right now.",
  "لم تتم إضافة أي طالب بعد.": "No students have been added yet.",
  "عرض الملف": "View profile",
  "تعذر تحميل المعلمين المؤهلين للدعوة.": "Could not load teachers eligible for invitation.",
  "البريد مطلوب لإرسال الدعوة.": "Email is required to send the invitation.",
  "أدخل بريدًا إلكترونيًا صالحًا.": "Enter a valid email address.",
  "المعلم المؤهل": "Eligible teacher",
  "لا توجد حلقة نشطة": "No active class",
  "تعذر تفعيل الدعوة. قد تكون منتهية أو ملغاة، أو فُتح الرابط بحساب آخر.": "Could not activate the invitation. It may be expired, cancelled, or opened with another account.",
  "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل.": "Password must contain at least 8 characters.",
  "كلمتا المرور غير متطابقتين.": "Passwords do not match.",
  "تعذر تعيين كلمة المرور. قد يكون رابط الدعوة غير صالح.": "Could not set the password. The invitation link may be invalid.",
  "جارٍ تفعيل وصول ولي الأمر...": "Activating guardian access...",
  "جارٍ التحقق من رابط الدعوة...": "Checking invitation link...",
  "تعذر تغيير كلمة المرور. قد يكون رابط الاستعادة منتهيًا أو غير صالح.": "Could not change the password. The recovery link may be expired or invalid.",
  "تعذر تغيير كلمة المرور حاليًا. حاول مرة أخرى لاحقًا.": "Could not change the password right now. Try again later.",
  "جارٍ تحديث كلمة المرور...": "Updating password...",
  "حفظ كلمة المرور": "Save password",

  // Access gates and remaining directories
  "جارٍ التحقق من صلاحيات التقارير التعليمية...": "Checking academic report permissions...",
  "تعذر تحديد نطاق التقارير التعليمية": "Could not determine the academic report scope",
  "يلزم وصول فعلي إلى الحضور أو الحفظ والمراجعة لفتح التقارير التعليمية.": "Access to attendance or memorization and revision is required to open academic reports.",
  "تعذر التحقق من الصلاحيات": "Could not verify permissions",
  "تعذر التحقق من صلاحيات التقارير التعليمية حاليًا دون عرض أي بيانات.": "Could not verify academic report permissions right now, so no data was displayed.",
  "جارٍ التحقق من صلاحيات دليل الأعضاء...": "Checking member directory permissions...",
  "تعذر تحديد نطاق الأعضاء": "Could not determine the member scope",
  "لا تملك صلاحية عرض أعضاء المدرسة. يلزم members.view وprofiles.view معًا.": "You do not have permission to view school members. Both members.view and profiles.view are required.",
  "تعذر التحقق من صلاحية دليل الأعضاء حاليًا دون عرض أي بيانات.": "Could not verify member directory permissions right now, so no data was displayed.",
  "أكمل بيانات الدعوة المطلوبة.": "Complete the required invitation details.",
  "تم إرسال دعوة ولي الأمر بصورة آمنة.": "Guardian invitation sent securely.",
  "تعذر إرسال دعوة ولي الأمر حاليًا.": "Could not send the guardian invitation right now.",
  "بحث بالطالب أو الولي أو الفرع...": "Search by student, guardian, or branch...",
  "إرسال الدعوة": "Send invitation",
  "صورة بديلة لـ": "Alternative image for",
  "تعذر تحميل دليل الأعضاء": "Could not load the member directory",
  "بطاقات أعضاء المدرسة": "School member cards",
  "جارٍ تجهيز وجهة الدخول المناسبة...": "Preparing the appropriate destination...",
  "جارٍ العودة إلى تسجيل الدخول...": "Returning to sign in...",
  "جارٍ فتح ...": "Opening...",
  "تعذر التحقق من بوابة ولي الأمر حاليًا. حاول مرة أخرى لاحقًا.": "Could not verify guardian portal access right now. Try again later.",
  "لا توجد عضوية مدرسية أو علاقة ولي أمر نشطة متاحة لهذا الحساب.": "No active school membership or guardian relationship is available for this account.",
  "البحث بالاسم أو الهاتف أو البريد أو التخصص...": "Search by name, phone, email, or specialization...",
  "جارٍ تحميل قائمة المعلمين...": "Loading teachers...",
  "تعذر تحميل قائمة المعلمين حاليًا.": "Could not load the teacher list right now.",
  "لم تتم إضافة أي معلم بعد.": "No teachers have been added yet.",
  "لا توجد نتائج بحث مطابقة.": "No matching search results.",
  "تم إنشاء بيئة العرض التجريبية بنجاح.": "Demo environment created successfully.",
  "تم مسح بيانات العرض التجريبية ( طالب).": "Demo data cleared.",
  "تأكيد بدء الاستخدام الفعلي": "Confirm start of live use",
  "ابدأ الاستخدام الفعلي": "Start live use",
  "تعذر تعيين كلمة المرور. قد يكون رابط الدعوة منتهيًا أو غير صالح.": "Could not set the password. The invitation link may be expired or invalid.",
  "حفظ كلمة المرور والدخول": "Save password and sign in",
  "تعذر إرسال رابط الاستعادة حاليًا. تحقق من البريد وحاول مرة أخرى.": "Could not send the recovery link. Check the email and try again.",
  "رابط الموقع غير مضاف في إعدادات Supabase. أضف https://quran-school-platform-livid.vercel.app/reset-password إلى Authentication ثم URL Configuration ثم Redirect URLs.": "The site URL is not configured in Supabase. Add https://quran-school-platform-livid.vercel.app/reset-password under Authentication, URL Configuration, and Redirect URLs.",
  "خدمة البريد في Supabase غير مفعلة حاليًا. فعّل Email Provider ثم أعد المحاولة.": "The Supabase email service is not enabled. Enable the Email Provider and try again.",
  "إذا كان البريد مرتبطًا بحساب، فسيصلك رابط لتغيير كلمة المرور.": "If the email is linked to an account, you will receive a password reset link.",
  "تعذر إرسال رابط الاستعادة حاليًا. حاول مرة أخرى لاحقًا.": "Could not send the recovery link right now. Try again later.",
  "إرسال رابط الاستعادة": "Send recovery link",
  "دليل الموظفين": "Employee directory",
  "سجل الأجور": "Payroll history",
  "تعذر التحقق من الوصول حاليًا. حاول مرة أخرى لاحقًا.": "Could not verify access right now. Try again later.",
  "لا توجد علاقة ولي أمر نشطة متاحة لهذا الحساب.": "No active guardian relationship is available for this account.",
  "جارٍ التحقق من صلاحيات الوثائق...": "Checking document permissions...",
  "لا تملك صلاحية الدخول إلى لوحة إدارة المدرسة.": "You do not have permission to access the school management dashboard.",
  "جارٍ التحقق من صلاحيات التسجيل...": "Checking registration permissions...",
  "جارٍ التحقق من صلاحيات الحساب...": "Checking account permissions...",
  "جارٍ التحقق من صلاحيات الطلاب...": "Checking student permissions...",

  // Treasury workspace
  "لا تملك صلاحية عرض الخزينة": "You do not have permission to view treasury",
  "يلزم finance.view أو finance.manage على المدرسة أو أحد الفروع.": "finance.view or finance.manage is required for the school or a branch.",
  "تعذر تحميل الخزينة.": "Could not load treasury.",
  "الخزينة والحسابات": "Treasury and accounts",
  "الرصيد مشتق من الحركات المنشورة؛ التحويل الداخلي لا يُحتسب إيرادًا أو مصروفًا.": "Balances are derived from posted transactions; internal transfers are not counted as income or expenses.",
  "حساب جديد": "New account",
  "الأرصدة الحالية": "Current balances",
  "صناديق نقدية وحسابات بنكية وبريدية ضمن نطاقك.": "Cash boxes, bank accounts, and postal accounts within your scope.",
  "إيراد آخر": "Other income",
  "تحويل": "Transfer",
  "إيداع/سحب": "Deposit / withdrawal",
  "لا توجد حسابات بعد. أنشئ أول صندوق/حساب برصيد افتتاحي صريح.": "No accounts yet. Create the first account with an explicit opening balance.",
  "أرشفة": "Archive",
  "الإيرادات غير الطلابية": "Non-student income",
  "تبرعات ومنح وأنشطة وتأجير أصول وإيرادات أخرى.": "Donations, grants, activities, asset rentals, and other income.",
  "لا توجد إيرادات أخرى.": "There is no other income.",
  "عكس": "Reverse",
  "آخر حركات الخزينة": "Latest treasury transactions",
  "السجل يثبت مكان دخول وخروج المال ولا يكرر الإيراد/المصروف في التقارير.": "The ledger records where money entered and left without duplicating income or expenses in reports.",
  "لا توجد حركات بعد.": "No transactions yet.",
  "التحويلات الداخلية": "Internal transfers",
  "كل تحويل = خروج من حساب + دخول إلى حساب بالقيمة نفسها.": "Each transfer equals an outflow from one account and an equal inflow to another.",
  "لا توجد تحويلات.": "No transfers.",
  "حساب خزينة جديد": "New treasury account",
  "الرصيد الافتتاحي يسجل كحركة مستقلة ولا يصبح عمودًا قابلًا للتعديل.": "The opening balance is recorded as a separate transaction and is not editable as a field.",
  "الرمز": "Code",
  "رقم/مرجع الحساب": "Account number / reference",
  "الرصيد الافتتاحي": "Opening balance",
  "تاريخ الرصيد": "Balance date",
  "إنشاء الحساب": "Create account",
  "إيراد غير طلابي": "Non-student income",
  "الإيراد يسجل مرة واحدة، وحركة الخزينة تحدد فقط أين دخل المال.": "Income is recorded once; the treasury transaction only identifies where the money entered.",
  "حساب القبض": "Receiving account",
  "الفئة": "Category",
  "طريقة القبض": "Collection method",
  "تسجيل الإيراد": "Record income",
  "تحويل داخلي": "Internal transfer",
  "التحويل لا يدخل في الإيرادات أو المصروفات.": "Transfers are not included in income or expenses.",
  "تنفيذ التحويل": "Complete transfer",
  "إيداع / سحب يدوي": "Manual deposit / withdrawal",
  "للتسويات النقدية فقط؛ لا يُسجل كإيراد أو مصروف تجاري.": "For cash adjustments only; not recorded as operating income or expense.",
  "إيداع": "Deposit",
  "سحب": "Withdrawal",
  "تسجيل الحركة": "Record transaction",

  // Core finance tables and forms
  "عرض فقط": "View only",
  "جارٍ تحميل الاستحقاقات": "Loading charges",
  "لا تملك صلاحية عرض الاستحقاقات": "You do not have permission to view charges",
  "يلزم finance.view أو finance.manage ضمن فرع مصرح به.": "finance.view or finance.manage is required in an authorized branch.",
  "تعذر تحميل الاستحقاقات حاليًا.": "Could not load charges right now.",
  "لا توجد استحقاقات بعد": "No charges yet",
  "أنشئ أول استحقاق لطالب في أحد الفروع التي تملك صلاحية إدارتها.": "Create the first charge for a student in a branch you can manage.",
  "جميع خطط الرسوم": "All fee plans",
  "الاستحقاق من": "Due from",
  "الاستحقاق إلى": "Due to",
  "لا توجد استحقاقات مطابقة للبحث والتصفية.": "No charges match the search and filters.",
  "الخطة": "Plan",
  "المبالغ": "Amounts",
  "الفرع والملاحظات": "Branch and notes",
  "الإجراءات": "Actions",
  "المبلغ الأصلي": "Original amount",
  "الخصم": "Discount",
  "تاريخ الاستحقاق": "Due date",
  "المالية / الاستحقاقات": "Finance / charges",
  "الرسوم والخصومات ضمن الفروع المصرح بها": "Fees and discounts within authorized branches",
  "تُحسب القيمة الصافية تلقائيًا، وتبقى هوية الطالب والفرع ثابتة بعد الإنشاء.": "The net amount is calculated automatically; the student and branch remain fixed after creation.",
  "نوع الاستحقاق": "Charge type",
  "المبلغ الأصلي (دج)": "Original amount (DZD)",
  "نوع الخصم": "Discount type",
  "سبب الخصم": "Discount reason",
  "بداية الفترة (اختياري)": "Period start (optional)",
  "نهاية الفترة (اختياري)": "Period end (optional)",
  "المبلغ الصافي المتوقع": "Expected net amount",
  "الرواتب غير متاحة": "Payroll unavailable",
  "يلزم finance.view أو finance.manage في نطاق مالي مسموح.": "finance.view or finance.manage is required in an authorized finance scope.",
  "المالية · الأجور": "Finance · Payroll",
  "رواتب المعلمين والإداريين": "Teacher and staff payroll",
  "مسير شهري مدقّق: الراتب الأساسي + الزيادات − الخصومات − السلف.": "Audited monthly payroll: base salary + additions − deductions − advances.",
  "حالة المسير": "Payroll run status",
  "إنشاء مسير الشهر": "Create monthly payroll run",
  "جارٍ تحميل الرواتب...": "Loading payroll...",
  "تعذر تحميل بيانات الرواتب حاليًا.": "Could not load payroll data right now.",
  "إعداد راتب جديد": "New salary setup",
  "عند تغيير الراتب، أنهِ سريان الإعداد القديم وأنشئ إعدادًا جديدًا بتاريخ سريان جديد. لا تُعدّل التاريخ الماضي.": "When changing salary, end the old setup and create a new one with a new effective date. Do not alter history.",
  "المعلم / الإداري": "Teacher / staff member",
  "الراتب الأساسي": "Base salary",
  "تاريخ السريان": "Effective date",
  "حفظ إعداد الراتب": "Save salary setup",
  "التعديل متاح في المسودة فقط، والدفع بعد الاعتماد فقط.": "Editing is available only in draft; payment is available only after approval.",
  "لا توجد بنود لهذا الشهر. تأكد من إعداد الرواتب ثم أنشئ أو أعد توليد المسير وهو مسودة.": "There are no items for this month. Check salary setups, then create or regenerate the draft payroll run.",
  "المستفيد": "Beneficiary",
  "الأساسي": "Base",
  "زيادات": "Additions",
  "خصومات": "Deductions",
  "سلف": "Advances",
  "إعدادات الرواتب": "Salary setups",
  "السجل التاريخي محفوظ ولا يُحذف.": "Historical records are preserved and not deleted.",
  "لا توجد إعدادات راتب في هذا النطاق.": "There are no salary setups in this scope.",
  "إنهاء السريان": "End effective period",
  "اعتماد المسير": "Approve payroll run",
  "إلغاء المسير": "Cancel payroll run",
  "إغلاق المسير": "Close payroll run",
  "مرجع الدفع": "Payment reference",
  "سبب عكس الدفع": "Payment reversal reason",
  "عكس الدفع": "Reverse payment",
  "جميع الطلاب": "All students",
  "جميع طرق الدفع": "All payment methods",
  "مسح التصفية": "Clear filters",
  "الطالب والاستحقاق": "Student and charge",
  "مبلغ الاستحقاق": "Charge amount",
  "مدفوع سابقًا": "Previously paid",
  "الرصيد المتبقي": "Remaining balance",
  "مبلغ الدفعة": "Payment amount",
  "الرقم المرجعي": "Reference number",
  "جارٍ تحميل الدفعات": "Loading payments",
  "لا تملك صلاحية عرض الدفعات": "You do not have permission to view payments",
  "يلزم finance.view أو finance.manage في فرع واحد على الأقل.": "finance.view or finance.manage is required in at least one branch.",
  "تعذر تحميل سجل الدفعات.": "Could not load payment history.",
  "لا توجد دفعات مسجلة": "No payments recorded",
  "يمكن تسجيل أول دفعة عند وجود استحقاق مفتوح في فرع تملك فيه finance.manage.": "You can record the first payment when an open charge exists in a branch where you have finance.manage.",
  "لا توجد دفعات مطابقة للبحث والتصفية.": "No payments match the search and filters.",
  "المالية / الدفعات": "Finance / payments",
  "سجل محاسبي كامل مع دعم السداد الجزئي والعكس": "Complete accounting history with partial payment and reversal support",
  "تسجيل دفعة جديدة": "Record new payment",
  "تظهر الاستحقاقات المفتوحة فقط، وتتحقق قاعدة البيانات نهائيًا من الرصيد والحالة.": "Only open charges are shown; the database performs the final balance and status check.",
  "الاستحقاق المفتوح": "Open charge",
  "اختر الاستحقاق": "Choose charge",
  "لا توجد استحقاقات مفتوحة لهذا الطالب.": "There are no open charges for this student.",
  "سداد الرصيد كاملًا": "Pay full balance",
  "جارٍ تحميل خطط الرسوم": "Loading fee plans",
  "لا تملك صلاحية عرض خطط الرسوم": "You do not have permission to view fee plans",
  "يلزم finance.view أو finance.manage على المدرسة أو أحد فروعها.": "finance.view or finance.manage is required for the school or one of its branches.",
  "تعذر تحميل خطط الرسوم حاليًا.": "Could not load fee plans right now.",
  "لا توجد خطط رسوم بعد": "No fee plans yet",
  "أضف أول خطة رسوم عامة للمدرسة أو خاصة بفرع عند توفر صلاحية الإدارة.": "Add the first school-wide or branch-specific fee plan when you have management access.",
  "إضافة خطة": "Add plan",
  "جميع دورات الفوترة": "All billing cycles",
  "لا توجد خطط مطابقة للبحث والتصفية.": "No plans match the search and filters.",
  "الفوترة": "Billing",
  "دورة الفوترة": "Billing cycle",
  "المالية / خطط الرسوم": "Finance / fee plans",
  "خطط عامة للمدرسة أو مخصصة لأحد الفروع": "School-wide or branch-specific plans",
  "جميع المبالغ بالدينار الجزائري. نطاق الخطة لا يمكن تغييره بعد الإنشاء.": "All amounts are in Algerian dinars. Plan scope cannot be changed after creation.",
  "نطاق الخطة": "Plan scope",
  "النطاق ثابت لحماية ارتباطات الخطة المالية.": "The scope is fixed to protect the plan’s financial links.",
  "اسم الخطة": "Plan name",
  "المبلغ (د.ج)": "Amount (DZD)",
  "يوم الاستحقاق": "Due day",

  // Discounts and finance overview
  "خصومات الحالات الاجتماعية والإخوة": "Social and sibling discounts",
  "خصم قابل للتحديد بالنسبة أو بالدينار للتلميذ المحتاج أو للأسرة التي لديها أكثر من ابن.": "A percentage or fixed DZD discount for a student in need or a family with multiple children.",
  "إدارة الخصومات": "Manage discounts",
  "سياسات تخفيض الاشتراك": "Fee discount policies",
  "تحدد المدرسة قيمة الخصم. سياسة واحدة نشطة من نوع اجتماعي أو إخوة تُطبّق تلقائيًا على الاشتراك الدوري بعد المعاينة والتأكيد، ولا تُجمع خصومات متعددة بصمت.": "The school sets the discount. One active social or sibling policy is applied automatically to recurring fees after preview and confirmation; multiple discounts are not silently combined.",
  "جارٍ تحميل الطلاب وسياسات الخصم...": "Loading students and discount policies...",
  "تعذر تحميل سياسات الخصم.": "Could not load discount policies.",
  "إضافة خصم لطالب": "Add student discount",
  "النظام لا يقرر أن الطالب محتاج من تلقاء نفسه. المسؤول المخول يثبت الأهلية ويحدد القيمة والمدة والسبب.": "The system does not decide whether a student is in need. An authorized manager confirms eligibility and sets the value, period, and reason.",
  "لا يوجد طلاب نشطون في الفروع التي تملك إدارتها المالية.": "There are no active students in branches you can manage financially.",
  "سبب الاستحقاق": "Eligibility reason",
  "حالة اجتماعية / طالب محتاج": "Social case / student in need",
  "أكثر من ابن / خصم إخوة": "Multiple children / sibling discount",
  "طريقة الخصم": "Discount method",
  "مبلغ ثابت بالدينار": "Fixed DZD amount",
  "قيمة الخصم": "Discount value",
  "يبدأ من": "Starts on",
  "ينتهي في — اختياري": "Ends on — optional",
  "سبب/ملاحظة موثقة": "Documented reason / note",
  "لن يُجمع خصمان تلقائيًا لنفس الفترة.": "Two discounts will not be combined automatically for the same period.",
  "سجل سياسات الخصم": "Discount policy history",
  "الإيقاف لا يحذف السياسة؛ يبقى سببها وقيمتها وتاريخها محفوظًا.": "Deactivation does not delete a policy; its reason, value, and history remain preserved.",
  "لا توجد سياسات خصم مسجلة في نطاقك.": "There are no discount policies recorded in your scope.",
  "لا تملك صلاحية عرض المالية": "You do not have permission to view finance",
  "يلزم منح الحساب finance.view أو finance.manage للتقارير المالية، أو finance.expenses للمصروفات.": "Grant finance.view or finance.manage for finance reports, or finance.expenses for expenses.",
  "تعذر تحميل بيانات المالية حاليًا.": "Could not load finance data right now.",
  "لا توجد بيانات مالية بعد": "No finance data yet",
  "ستظهر هنا الرسوم والدفعات والمصروفات تلقائيًا عند توفرها في قاعدة البيانات.": "Fees, payments, and expenses will appear here automatically when available.",
  "عرض وإدارة الخطط العامة للمدرسة والخطط الخاصة بالفروع.": "View and manage school-wide and branch-specific plans.",
  "فتح خطط الرسوم": "Open fee plans",
  "عرض الرسوم والخصومات وإنشاء الاستحقاقات ضمن الفروع المصرح بها.": "View fees and discounts and create charges within authorized branches.",
  "فتح الاستحقاقات": "Open charges",
  "تسجيل الدفعات الجزئية والكاملة وعكس القيود مع حفظ السجل المحاسبي.": "Record partial and full payments and reverse entries while preserving accounting history.",
  "فتح الدفعات": "Open payments",
  "تسجيل المصروفات المدرسية والفرعية وتعديلها أو إلغاؤها دون حذف السجل المحاسبي.": "Record, edit, or cancel school and branch expenses without deleting accounting history.",
  "فتح المصروفات": "Open expenses",
  "التقارير المالية": "Financial reports",
  "الاستحقاقات والتحصيلات والمتأخرات والمصروفات وصافي التدفق حسب الصلاحيات الفعلية.": "Charges, collections, overdue balances, expenses, and net cash flow based on actual permissions.",
  "فتح التقارير": "Open reports",
  "حالة الوصول المالي": "Finance access status",
  "تُعرض البيانات ضمن المدرسة والفروع المصرح بها فقط.": "Data is shown only for authorized school and branch scopes.",
  "ملخص المالية": "Finance summary",
  "نظرة فورية على الاستحقاقات والتحصيل والمصروفات": "A quick view of charges, collections, and expenses",

  // Expense and reporting screens
  "جميع التصنيفات": "All categories",
  "تاريخ المصروف": "Expense date",
  "جارٍ تحميل المصروفات...": "Loading expenses...",
  "لا تملك صلاحية المصروفات": "You do not have expense permission",
  "يلزم منح finance.expenses على المدرسة أو أحد الفروع. لا تُستخدم finance.view أو finance.manage لهذا القسم.": "finance.expenses is required for the school or a branch. finance.view and finance.manage do not grant access to this section.",
  "تعذر تحميل المصروفات الحقيقية حاليًا.": "Could not load actual expenses right now.",
  "المصروفات الظاهرة": "Visible expenses",
  "إجمالي المسجل": "Total recorded",
  "نطاق الصلاحية": "Permission scope",
  "لا توجد مصروفات": "No expenses",
  "لا توجد قيود مطابقة للفلاتر الحالية، أو لم تُسجّل مصروفات بعد.": "No entries match the current filters, or no expenses have been recorded yet.",
  "إدارة المصروفات": "Expense management",
  "قيود حقيقية من Supabase ضمن نطاق finance.expenses": "Actual Supabase entries within the finance.expenses scope",
  "المصروف الملغى لا يمكن تعديله أو إعادته إلى مسجل من الواجهة.": "A cancelled expense cannot be edited or restored from the interface.",
  "الفرع أو مستوى المدرسة": "Branch or school level",
  "المبلغ بالدينار الجزائري": "Amount in Algerian dinars",
  "جارٍ إعداد التقارير المالية...": "Preparing finance reports...",
  "لا تملك صلاحية التقارير": "You do not have report permission",
  "يلزم finance.view أو finance.manage للتقارير المالية العامة، أو finance.expenses لتقرير المصروفات.": "finance.view or finance.manage is required for general finance reports, or finance.expenses for the expense report.",
  "تعذر تحميل التقارير المالية.": "Could not load finance reports.",
  "تقرير المصروفات وصافي التدفق مخفيان لعدم وجود finance.expenses.": "Expense and net cash-flow reports are hidden because finance.expenses is missing.",
  "الاستحقاقات والتحصيلات والرواتب مخفية لعدم وجود finance.view أو finance.manage.": "Charges, collections, and payroll are hidden because finance.view or finance.manage is missing.",
  "التحصيلات والمصروفات والرواتب ضمن الصلاحيات الحالية": "Collections, expenses, and payroll within current permissions",
  "تقرير مالي": "Finance report",
  "كل النطاقات المسموحة": "All authorized scopes",
  "كل حالات الاستحقاق": "All charge statuses",
  "كل طرق الدفع": "All payment methods",
  "كل تصنيفات المصروف": "All expense categories",
  "مسح الفلاتر": "Clear filters",
  "لا توجد بيانات مطابقة للفلاتر الحالية.": "No data matches the current filters.",
  "صافي المبلغ": "Net amount",
  "الطريقة": "Method",
  "المسدد": "Paid amount",
  "الملخصات التحليلية": "Analytics summaries",
  "التحصيل": "Collections",
  "تشغيلي": "Operating",
  "لا توجد بيانات.": "No data.",
  "القيمة": "Value",
  "القوائم المالية الشهرية": "Monthly financial statements",
  "قائمة رسمية مشتقة من العمليات الفعلية، مع فصل نتيجة الأعمال عن مكان حركة النقد.": "An official statement derived from actual transactions, separating operating results from cash location.",
  "تعذر عرض القائمة.": "Could not display the statement.",
  "حالة الفترة": "Period status",
  "أنت ترى نطاق الفروع المصرح لك بها فقط. أرصدة الخزينة وتفاصيل الحسابات أدناه تخص الحسابات الظاهرة لك، ولا يتم إظهار حسابات مدرسية مركزية خارج صلاحيتك.": "You only see authorized branches. Treasury balances and account details below apply to visible accounts; central school accounts outside your scope are not shown.",
  "الاستحقاق والتحصيل ونتيجة التشغيل": "Charges, collections, and operating result",
  "التدفقات والخزينة": "Cash flows and treasury",
  "استحقاقات": "Charges",
  "تحصيلات": "Collections",
  "مصروفات": "Expenses",
  "رواتب مستحقة": "Payroll due",
  "رواتب مدفوعة": "Payroll paid",
  "تفصيل حسابات الخزينة": "Treasury account breakdown",
  "افتتاحي": "Opening",
  "قيد افتتاحي": "Opening entry",
  "داخل": "Inflow",
  "خارج": "Outflow",
  "تحويل داخل": "Transfer in",
  "تحويل خارج": "Transfer out",
  "ختامي": "Closing",

  // Recurring billing and roster assignments
  "كل فروع المدرسة": "All school branches",
  "الاستحقاقات الدورية والتذكيرات": "Recurring charges and reminders",
  "معاينة أولًا، ثم تأكيد صريح قبل إنشاء أي رسوم أو تنبيه.": "Preview first, then explicitly confirm before creating any fees or alerts.",
  "إدارة الدوري والتذكيرات": "Manage recurring billing and reminders",
  "الاستحقاقات الدورية وتذكيرات الأولياء": "Recurring charges and guardian reminders",
  "لا تُنشأ رسوم ولا إشعارات بمجرد فتح هذه النافذة. كل عملية تمر بمعاينة ثم تأكيد مستقل، والخصومات الاجتماعية/الإخوة المفعلة تظهر قبل الإنشاء.": "Opening this window creates no fees or notifications. Each operation requires a preview and separate confirmation, and active social or sibling discounts are shown before creation.",
  "جارٍ تحميل نطاقات المالية والخطط الدورية...": "Loading finance scopes and recurring plans...",
  "تعذر تحميل إعدادات المالية.": "Could not load finance settings.",
  "1. توليد الاستحقاقات الدورية": "1. Generate recurring charges",
  "الخطط الشهرية والربع سنوية والسنوية فقط. الطالب النشط يُضاف مرة واحدة لكل خطة وفترة.": "Monthly, quarterly, and annual plans only. An active student is added once per plan and period.",
  "لا توجد خطة رسوم دورية نشطة في نطاقاتك. أنشئ أو فعّل خطة شهرية/ربع سنوية/سنوية أولًا.": "There is no active recurring fee plan in your scope. Create or activate a monthly, quarterly, or annual plan first.",
  "خطة الرسوم": "Fee plan",
  "نطاق التوليد": "Generation scope",
  "تاريخ داخل الفترة المطلوبة": "Date within the required period",
  "إعادة التأكيد لن تنشئ نسخة مكررة لنفس الطالب والخطة والفترة.": "Confirming again will not create a duplicate for the same student, plan, and period.",
  "تحديث قائمة الاستحقاقات": "Refresh charge list",
  "2. تذكيرات الاستحقاق والمتأخرات": "2. Due and overdue reminders",
  "تُرسل داخل مركز إشعارات ولي الأمر الحالي فقط. المدفوع والمعفى والملغى لا يدخل في التذكيرات.": "Sent only through the current guardian notification center. Paid, waived, and cancelled charges are excluded.",
  "الاحتساب حتى تاريخ": "Calculate through date",
  "قريب الاستحقاق خلال (أيام)": "Due soon within (days)",
  "ربط الطالب بالحلقة": "Link student to class",
  "اختر طالبًا نشطًا ثم عيّن له حلقة نشطة من فرعه نفسه، أو اتركه دون حلقة.": "Choose an active student, then assign an active class from the same branch or leave the student unassigned.",
  "دون حلقة": "No class",
  "لا تظهر إلا الحلقات النشطة التابعة لمدرسة الطالب وفرعه الحاليين.": "Only active classes in the student’s current school and branch are shown.",
  "تعيين المعلمين للحلقات": "Assign teachers to classes",
  "أضف معلمًا أساسيًا أو مساعدًا، غيّر دوره، أو عطّل التعيين دون حذف السجل.": "Add a primary or assistant teacher, change the role, or deactivate the assignment without deleting history.",
  "فرع الحلقة:": "Class branch:",
  "إضافة أو تحديث تعيين": "Add or update assignment",
  "اختيار معلم سبق تعطيل تعيينه سيعيد تفعيل السجل نفسه بدل إنشاء نسخة مكررة.": "Choosing a teacher whose assignment was deactivated will reactivate the same record instead of creating a duplicate.",
  "لا يوجد معلمون نشطون في فرع الحلقة.": "There are no active teachers in the class branch.",
  "الصفة": "Role",
  "التعيينات النشطة": "Active assignments",
  "تعيينات سابقة غير نشطة": "Previous inactive assignments",
  "إدارة الربط": "Manage links",

  // Invitations, period close, guardians, and memorization
  "دعوة معلم": "Invite teacher",
  "دعوة معلم موجود": "Invite existing teacher",
  "سيستخرج الخادم دور المعلم وفرعه واسمه من السجل الموجود، ولن تحفظ الواجهة البريد مباشرة.": "The server will derive the teacher’s role, branch, and name from the existing record; the interface will not save the email directly.",
  "جارٍ تحميل المعلمين المؤهلين...": "Loading eligible teachers...",
  "لا يوجد معلم مؤهل للدعوة": "No teacher is eligible for invitation",
  "يظهر هنا فقط المعلم النشط غير المربوط بحساب ودون دعوة نشطة.": "Only active teachers without a linked account or active invitation appear here.",
  "لا تملك الصلاحيات الثلاث المطلوبة لإرسال دعوة معلم.": "You do not have the three permissions required to send a teacher invitation.",
  "تم تجهيز الدعوة بأمان. سيختفي المعلم من قائمة المؤهلين، ولا تُرسل دعوة أخرى عند إعادة العرض.": "Invitation prepared securely. The teacher will leave the eligible list, and reopening will not send another invitation.",
  "الدور الثابت": "Fixed role",
  "الحلقات المرتبطة": "Linked classes",
  "بريد الدعوة": "Invitation email",
  "سترسل الدعوة إلى هذا البريد فقط بعد نجاح Auth والتجهيز الذري.": "The invitation will be sent to this email only after Auth and atomic preparation succeed.",
  "جارٍ إرسال الدعوة...": "Sending invitation...",
  "إقفال الفترة المالية": "Financial period close",
  "إقفال شهري مدقق: مطابقة الخزينة أولًا، ثم منع أي تعديل عادي بتاريخ يعود للفترة.": "Audited monthly close: reconcile treasury first, then block ordinary changes dated within the period.",
  "إغلاق نهائي": "Final close",
  "إعادة فتح للتصحيح": "Reopen for correction",
  "عند بدء الإقفال يتوقف التسجيل أو التعديل العادي بتاريخ داخل الشهر. إذا ظهر فرق، أعد فتح الفترة بسبب موثق، سجّل التصحيح، ثم أعد المطابقة والإقفال. المطابقات القديمة تبقى محفوظة.": "Once closing starts, ordinary entries and edits dated within the month stop. If a difference appears, reopen with a documented reason, record the correction, then reconcile and close again. Previous reconciliations remain preserved.",
  "مطابقة حسابات الخزينة": "Reconcile treasury accounts",
  "الصندوق يطابق العد النقدي، والحساب البنكي/البريدي يطابق كشف الحساب المؤرخ بنهاية الفترة.": "Cash boxes reconcile against cash counts; bank and postal accounts reconcile against period-end statements.",
  "لا توجد حسابات خزينة ظاهرة ضمن صلاحياتك.": "No treasury accounts are visible within your permissions.",
  "رصيد النظام بنهاية الفترة": "System balance at period end",
  "آخر رصيد فعلي": "Latest actual balance",
  "الفرق:": "Difference:",
  "تسجيل مطابقة جديدة": "Record new reconciliation",
  "سجل أحداث الفترة": "Period event history",
  "جارٍ تحميل بيانات الأولياء...": "Loading guardian data...",
  "لا تملك صلاحية عرض روابط أولياء الطلبة في نطاقك الحالي.": "You do not have permission to view student-guardian links in your current scope.",
  "إدارة روابط أولياء الأمور ودعواتهم ومتابعة حالة التفعيل.": "Manage guardian links and invitations and follow activation status.",
  "دعوة ولي أمر": "Invite guardian",
  "تعذر تحميل بيانات الأولياء. أعد المحاولة.": "Could not load guardian data. Try again.",
  "إجمالي الروابط": "Total links",
  "نشطة": "Active",
  "بانتظار التفعيل": "Awaiting activation",
  "روابط الأولياء": "Guardian links",
  "لا توجد روابط أولياء مطابقة.": "No matching guardian links.",
  "ولي أساسي": "Primary guardian",
  "اختر الطالب ثم أدخل هوية ولي الأمر. سيصل رابط تفعيل آمن إلى البريد.": "Choose the student, then enter the guardian identity. A secure activation link will be emailed.",
  "يمكن تعيين ولي أساسي واحد فقط للطالب.": "Only one primary guardian can be assigned to a student.",
  "نطاق المتابعة": "Follow-up scope",
  "اختر التاريخ والفرع والحلقة والطالب ضمن صلاحياتك.": "Choose the date, branch, class, and student within your permissions.",
  "لا توجد حلقات ضمن هذا الفرع": "There are no classes in this branch",
  "لا يوجد طلاب نشطون": "There are no active students",
  "وضع العرض فقط: يمكنك مشاهدة سجلات الطالب وسجل التدقيق، ولا تُرسل الصفحة أي عملية إنشاء أو تعديل.": "View-only mode: you can see student records and the audit trail; the page sends no create or update operation.",
  "الحفظ القادم سيعدّل السجل الحالي. استخدم «سجل جديد» لإضافة متابعة أخرى.": "The next save will update the current record. Use “New record” to add another follow-up.",
  "تم ربط السجل بحساب المعلم الحالي تلقائيًا.": "The record was linked automatically to the current teacher account.",
  "معلم السجل ثابت بعد الإنشاء ولا يمكن تغييره أثناء التعديل.": "The record’s teacher is fixed after creation and cannot be changed while editing.",
  "سجل الطالب السابق": "Student history",
  "الأخطاء": "Errors",
  "آخر تحديث": "Last updated",
  "جارٍ تحميل سجل التدقيق...": "Loading audit trail...",
  "لا توجد حركات تدقيق متاحة.": "No audit events are available.",

  // Account activation and reconciliation
  "تم تفعيل وصول ولي الأمر بنجاح": "Guardian access activated successfully",
  "تم ربط الحساب بأمان. يمكنك الآن متابعة الأبناء المرتبطين بحسابك.": "The account was linked securely. You can now follow the children linked to your account.",
  "متابعة إلى حسابي": "Continue to my account",
  "رابط الدعوة غير صالح": "Invalid invitation link",
  "قد تكون الدعوة منتهية أو ملغاة، أو فُتح الرابط بحساب غير مخصص لها.": "The invitation may be expired, cancelled, or opened with an account it was not intended for.",
  "تعذر إكمال التفعيل": "Could not complete activation",
  "تفعيل حساب ولي الأمر": "Activate guardian account",
  "عيّن كلمة مرور قوية لإكمال تفعيل الحساب الجديد.": "Set a strong password to finish activating the new account.",
  "تأكيد كلمة المرور": "Confirm password",
  "حفظ كلمة المرور وتفعيل الوصول": "Save password and activate access",
  "رابط الدعوة منتهي أو غير صالح، أو لا توجد جلسة دعوة موثقة. لن يظهر نموذج كلمة المرور.": "The invitation link is expired or invalid, or there is no verified invitation session. The password form will not be shown.",
  "تم تعيين كلمة المرور": "Password set",
  "حُفظت كلمة المرور الجديدة، لكن تعذر تحديث حالة سجل الدعوة. يمكنك متابعة الدخول، وسيُراجع السجل بصورة مستقلة دون إعادة كلمة المرور.": "The new password was saved, but the invitation record status could not be updated. You can continue signing in; the record will be reviewed independently without resetting the password.",
  "متابعة الدخول": "Continue signing in",
  "قبول دعوة المعلم": "Accept teacher invitation",
  "عيّن كلمة مرور قوية لإكمال الدخول.": "Set a strong password to complete sign-in.",
  "الدور": "Role",
  "جارٍ إكمال الدعوة...": "Completing invitation...",
  "تعذر تحميل المطابقة.": "Could not load reconciliation.",
  "مطابقة الخزينة": "Treasury reconciliation",
  "نقارن العمليات التجارية بحركات الخزينة دون احتساب أي حركة مرتين.": "Compare operating transactions with treasury movements without counting any transaction twice.",
  "مصادر التدفق التجاري": "Operating cash-flow sources",
  "حركات لا تدخل في الإيراد/المصروف": "Transactions excluded from income / expenses",
  "التحويلات والتسويات تؤثر على أرصدة الحسابات فقط، ولا تغيّر صافي الإيراد/المصروف التجاري.": "Transfers and adjustments affect account balances only and do not change net operating income or expense.",
  "العمليات غير المربوطة بحساب": "Transactions not linked to an account",
  "اختر حسابًا فعليًا للعملية. الربط ينشئ حركة الخزينة تلقائيًا ويحفظ العملية الأصلية كما هي.": "Choose an actual account for the transaction. Linking automatically creates the treasury movement and preserves the original transaction.",
  "لا توجد عمليات تحتاج مطابقة.": "No transactions need reconciliation.",
  "لا يوجد حساب متوافق": "No compatible account",
  "أرصدة الحسابات": "Account balances",

  // Academic reports and member directory
  "كل الطلاب": "All students",
  "نظرة عامة": "Overview",
  "تحليلات المتابعة": "Follow-up analytics",
  "الأخير": "Latest",
  "آخر سجل": "Latest record",
  "· مراجعة:": "· Revision:",
  "آخر جلسة": "Latest session",
  "السورة والآيات": "Surah and verses",
  "الغياب": "Absence",
  "التأخر": "Lateness",
  "أنت": "You",
  "جارٍ تحميل أعضاء المدرسة...": "Loading school members...",
  "لا توجد عضويات متاحة": "No memberships available",
  "لم تُرجع سياسات المدرسة أي عضوية غير ملغاة للعرض.": "School policies returned no non-cancelled memberships to display.",
  "نطاق الفرع": "Branch scope",
  "إظهار الأعضاء دون أدوار فقط": "Show only members without roles",
  "جرّب تعديل البحث أو حالة العضوية أو الدور أو الفرع.": "Try changing the search, membership status, role, or branch.",
  "التواريخ": "Dates",
  "دليل للعرض فقط وفق صلاحيات المدرسة وسياسات RLS الحالية.": "A view-only directory based on school permissions and current RLS policies.",

  // Guardian student pages, analytics, demo, and notes
  "الطالب غير متاح": "Student unavailable",
  "لا توجد علاقة ولي أمر نشطة تسمح بعرض هذا الطالب.": "No active guardian relationship allows viewing this student.",
  "العودة إلى أبنائي": "Back to my children",
  "تعذر جلب بيانات الطالب حاليًا.": "Could not retrieve student data right now.",
  "لا توجد سجلات حضور بعد.": "No attendance records yet.",
  "لا توجد سجلات حفظ أو مراجعة بعد.": "No memorization or revision records yet.",
  "التكليف القادم:": "Next assignment:",
  "لا توجد استحقاقات مالية مسجلة.": "No financial charges recorded.",
  "سجل المدفوعات": "Payment history",
  "لا توجد مدفوعات مسجلة.": "No payments recorded.",
  "كل الأنواع": "All types",
  "كل الأولويات": "All priorities",
  "جارٍ تحليل ملاحظات الحفظ...": "Analyzing memorization notes...",
  "غير معالجة": "Unresolved",
  "متكررة": "Repeated",
  "الحلقة الحالية": "Current class",
  "لا توجد تغييرات حالة موثقة في هذه الفترة.": "No documented status changes in this period.",
  "لا توجد ملاحظات عالية الأولوية ضمن الفلاتر الحالية.": "No high-priority notes match the current filters.",
  "التحليلات قراءة فقط ومشتقة من سجل المتابعة؛ لا تُنشئ تقييمات أو توصيات آلية جديدة.": "Analytics are read-only and derived from follow-up history; they do not create new automated ratings or recommendations.",
  "تعذر تحميل بيانات الأبناء": "Could not load children’s data",
  "تعذر جلب البيانات حاليًا. لم يتم عرض أي بيانات بديلة.": "Could not retrieve data right now. No fallback data was shown.",
  "المتابعة الأسرية": "Family follow-up",
  "أبنائي": "My children",
  "تابع الحضور والحفظ لكل طالب مرتبط بحسابك. لا تظهر هنا إلا العلاقات النشطة.": "Follow attendance and memorization for each student linked to your account. Only active relationships appear here.",
  "عدد الأبناء المرتبطين": "Linked children",
  "لا توجد علاقات نشطة": "No active relationships",
  "عند تفعيل ربط أحد الأبناء سيظهر هنا تلقائيًا.": "A child will appear here automatically when the link is activated.",
  "عرض المتابعة الأكاديمية": "View academic follow-up",
  "جارٍ التحقق من وضع العرض التجريبي...": "Checking demo mode...",
  "وضع العرض التجريبي": "Demo mode",
  "اعرض للزبون منصة ممتلئة وجاهزة خلال ثوانٍ": "Show a fully populated, ready platform in seconds",
  "ينشئ النظام 20 طالبًا، معلمين، حلقتين، حضورًا، حفظًا وبيانات مالية مترابطة. كل ما ينشئه العرض يُتتبع منفصلًا عن بيانات المدرسة الحقيقية ويمكن مسحه لاحقًا بأمان.": "The system creates 20 students, teachers, two classes, attendance, memorization, and linked finance data. Everything created by the demo is tracked separately from live school data and can be cleared safely later.",
  "البيانات التجريبية مفعلة": "Demo data is active",
  "أنت الآن تستعرض نموذجًا جاهزًا للعمل": "You are viewing a ready-to-use demo",
  "استخدم الطلاب والمعلمين والحلقات التجريبية للاستكشاف والتدريب فقط؛ أي حضور أو حفظ أو حركة مالية تسجل عليها تُعامل كجزء من العرض وقد تُمسح معه. ابدأ إدخال البيانات الحقيقية بعد إنهاء وضع العرض، ولا تربط كيانات Demo بدعوات أو علاقات حقيقية.": "Use demo students, teachers, and classes only for exploration and training. Any attendance, memorization, or finance transaction recorded on them is part of the demo and may be cleared with it. Enter live data after ending demo mode, and do not link demo entities to real invitations or relationships.",
  "للتأكيد اضغط الزر مرة ثانية. سيحذف النظام كيانات العرض التجريبية والسجلات التابعة لها، ويوقف العملية إذا اكتشف خلطًا محميًا مع طالب أو ولي أمر أو دعوة حقيقية.": "Select the button again to confirm. The system will remove demo entities and their records, and stop if it detects protected mixing with a real student, guardian, or invitation.",
  "إذا تكرر نفس النوع في نفس نطاق الآيات لاحقًا فسيزيد عداد التكرار تلقائيًا.": "If the same type recurs in the same verse range, the repeat counter increases automatically.",
  "يمكن إدراج أكثر من ملاحظة في الجلسة نفسها، ويُحفظ كل بند مستقلًا في السجل.": "You can add multiple notes in the same session; each item is saved independently in history.",
  "جارٍ تحميل نقاط التركيز...": "Loading focus points...",
  "لا توجد نقاط مفتوحة تحتاج تركيزًا خاصًا لهذا الطالب حاليًا.": "There are no open points requiring special attention for this student right now.",
  "سجل ملاحظات وأخطاء الطالب": "Student notes and errors history",
  "يحتفظ بالسجل السابق حتى بعد التحسن أو المعالجة، ولا توجد عملية حذف من الواجهة.": "History is preserved even after improvement or resolution; the interface provides no delete action.",
  "جارٍ تحميل سجل الملاحظات...": "Loading notes history...",
  "لا توجد ملاحظات سابقة لهذا الطالب.": "There are no previous notes for this student.",

  // Payroll history, password recovery, attendance, and gates
  "تاريخ مسيرات المعلمين والإداريين مع أثر الدفع والعكس، قراءة فقط.": "Read-only teacher and staff payroll history with payment and reversal audit trail.",
  "كل المستفيدين": "All beneficiaries",
  "سجل الأجور غير متاح": "Payroll history unavailable",
  "يلزم finance.view أو finance.manage في هذا النطاق.": "finance.view or finance.manage is required in this scope.",
  "تعذر تحميل سجل الأجور.": "Could not load payroll history.",
  "لا توجد أجور تاريخية في هذا النطاق.": "There is no payroll history in this scope.",
  "حالة البند": "Item status",
  "الدفع": "Payment",
  "جارٍ التحقق من رابط الاستعادة...": "Checking recovery link...",
  "رابط الاستعادة غير صالح أو انتهت صلاحيته.": "The recovery link is invalid or expired.",
  "العودة إلى استعادة كلمة المرور": "Back to password recovery",
  "تعيين كلمة مرور جديدة": "Set a new password",
  "اختر كلمة مرور قوية لا تقل عن 8 أحرف.": "Choose a strong password of at least 8 characters.",
  "كلمة المرور الجديدة": "New password",
  "الحضور اليومي": "Daily attendance",
  "وضع العرض فقط: يمكنك مشاهدة السجل والملخص، ولا تُرسل الصفحة أي عملية إنشاء أو تعديل.": "View-only mode: you can see the history and summary; the page sends no create or update operation.",
  "تعيين الجميع حاضرًا": "Mark everyone present",
  "وقت الوصول": "Arrival time",
  "ملاحظة قصيرة": "Short note",
  "جارٍ تحميل ملف الطالب...": "Loading student profile...",
  "المستوى التعليمي": "Education level",
  "جارٍ التحقق من صلاحيات الحضور...": "Checking attendance permissions...",
  "تعذر تحديد نطاق الحضور": "Could not determine the attendance scope",
  "جارٍ التحقق من صلاحيات متابعة الحفظ...": "Checking memorization follow-up permissions...",
  "تعذر تحديد نطاق متابعة الحفظ": "Could not determine the memorization follow-up scope",
  "جارٍ التحقق من وصول ولي الأمر...": "Checking guardian access...",
  "تعذر فتح بوابة ولي الأمر": "Could not open the guardian portal",
  "أهلاً بك في QuranOS": "Welcome to QuranOS",
  "جارٍ تحميل بيانات لوحة التحكم...": "Loading dashboard data...",
  "العودة إلى وجهة الحساب": "Back to account destination",
  "تعذر تحديد نطاق المالية": "Could not determine the finance scope",
  "جارٍ التحقق من جلسة الدخول...": "Checking sign-in session...",
  "تعذر فتح لوحة الإدارة": "Could not open the management dashboard",
  "لا توجد وجهة متاحة": "No destination available",
  "العودة إلى تسجيل الدخول": "Back to sign in",
  "إضافة مصروف": "Add expense",
  "استحقاقات الطلاب": "Student charges",
  "الدفعات والتحصيل": "Payments and collections",
  "الاستحقاق": "Charge",
  "استعادة كلمة المرور": "Password recovery",
  "أدخل بريد حسابك لإرسال رابط تغيير كلمة المرور.": "Enter your account email to receive a password reset link.",
  "تسجيل دفعة": "Record payment",
  "المدفوع سابقًا": "Previously paid",
  "إنشاء استحقاق": "Create charge",
  "من": "From",
  "إلى": "To",
  "التاريخ من": "Date from",
  "التاريخ إلى": "Date to",
  "حفظ:": "Memorization:",
  "المراجعة": "Revision",
  "اختر الفرع": "Choose branch",
  "حفظ الحلقة": "Save class",
  "جارٍ الحفظ...": "Saving...",
  "تعذر تحديد المدرسة الحالية.": "Could not identify the current school.",
  "السابق": "Previous",
  "حفظ المعلم": "Save teacher",
  "تعذر تسجيل الخروج حاليًا. حاول مرة أخرى.": "Could not sign out right now. Try again.",
  "تحديث الحالة": "Update status",
  "حفظ الحالة": "Save status",
  "تم حفظ الموظف.": "Employee saved.",
  "إضافة الموظف": "Add employee",
  "تصفية حسب الفرع": "Filter by branch",
  "تصفية حسب الحالة": "Filter by status",
  "حسب الفرع": "By branch",
  "جارٍ الإرسال...": "Sending...",
  "اختر الطالب": "Choose student",
  "اكتب اسم العضو": "Enter member name",
  "العضو": "Member",
  "السجل السابق": "Previous history",
  "تصفية حسب الطالب": "Filter by student",
  "اختر...": "Choose...",
  "الموظف": "Employee",
  "جارٍ تحميل السجل...": "Loading history...",
  "جارٍ تسجيل الخروج...": "Signing out...",
  "— آية  إلى": "— Verse to",
  "المحدد": "Selected",
  "حفظ الملاحظة": "Save note",
  "اختر الحلقة": "Choose class",
  "الفرع الحالي:": "Current branch:",
};
