-- QuranOS V2 - school backup private object storage
-- Stage 1: persist generated school backup packages in a private Supabase Storage bucket.
-- Scheduled backup and destructive restore remain separate stages.

begin;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'school-backups',
  'school-backups',
  false,
  52428800,
  array['application/json']
)
on conflict (id) do update
set public = false,
    file_size_limit = 52428800,
    allowed_mime_types = array['application/json'];

-- Object paths are always:
--   <school_id>/<snapshot_id>.json
-- Direct browser access is not granted; downloads use short-lived signed URLs
-- generated by the backup Edge Function with the server-only key.

create index if not exists school_backup_snapshots_storage_key_idx
  on public.school_backup_snapshots (storage_key)
  where storage_key is not null;

commit;
