import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const migrationPath=new URL("../supabase/042_memorization_follow_up_analytics.sql",import.meta.url);
const clientPath=new URL("../client/src/lib/memorization-analytics.ts",import.meta.url);
const componentPath=new URL("../client/src/components/MemorizationAnalyticsPanel.tsx",import.meta.url);
const reportsPath=new URL("../client/src/pages/AcademicReports.tsx",import.meta.url);
const runnerPath=new URL("./run-memorization-follow-up-migration-test.sh",import.meta.url);
const [migration,client,component,reports,runner]=await Promise.all([readFile(migrationPath,"utf8"),readFile(clientPath,"utf8"),readFile(componentPath,"utf8"),readFile(reportsPath,"utf8"),readFile(runnerPath,"utf8")]);

test("analytics migration stays read-only and scoped through existing memorization authorization",()=>{assert.match(migration,/create or replace function public\.get_memorization_follow_up_analytics/);assert.match(migration,/returns jsonb/);assert.match(migration,/stable\s+security definer/i);assert.match(migration,/public\.can_access_memorization_class\([\s\S]*?'memorization\.view'/);assert.match(migration,/public\.can_access_memorization_class\([\s\S]*?'memorization\.manage'/);assert.match(migration,/join scoped_students as scoped_student[\s\S]*?scoped_student\.id = note\.student_id/);assert.match(migration,/from public\.memorization_follow_up_note_history as history/);assert.match(migration,/history\.new_values ->> 'status'/);assert.match(migration,/grant execute on function public\.get_memorization_follow_up_analytics[\s\S]*?to authenticated/);assert.match(migration,/revoke execute on function public\.get_memorization_follow_up_analytics[\s\S]*?from anon/);assert.doesNotMatch(migration,/create table/i);assert.doesNotMatch(migration,/insert into public\.memorization_follow_up/i);assert.doesNotMatch(migration,/update public\.memorization_follow_up/i);assert.doesNotMatch(migration,/delete from public\.memorization_follow_up/i);});
test("analytics recurrence and trends are derived rather than persisted",()=>{assert.match(migration,/signature_counts as/);assert.match(migration,/count\(\*\)::bigint as recurrence_count/);assert.match(migration,/trend_rows as/);assert.doesNotMatch(migration,/recurrence_count\s+(?:integer|bigint|smallint)/i);});
test("browser analytics client uses only the scoped RPC",()=>{assert.match(client,/\.rpc\(\s*"get_memorization_follow_up_analytics"/);assert.doesNotMatch(client,/\.from\(\s*"memorization_follow_up_notes"/);assert.doesNotMatch(client,/\.from\(\s*"memorization_follow_up_note_history"/);assert.match(client,/target_category/);assert.match(client,/target_status/);assert.match(client,/target_priority/);});
test("analytics UI is integrated into academic reports with read-only insight sections",()=>{assert.match(component,/فلاتر أخطاء الحفظ/);assert.match(component,/أكثر أنواع الأخطاء/);assert.match(component,/المواضع الأكثر تكرارًا/);assert.match(component,/الطلاب الأعلى حاجة للمتابعة/);assert.match(component,/اتجاه التحسن/);assert.match(component,/أولوية المتابعة الآن/);assert.match(component,/قراءة فقط/);assert.doesNotMatch(component,/\.delete\(/);assert.doesNotMatch(component,/\.insert\(/);assert.doesNotMatch(component,/\.update\(/);assert.match(reports,/MemorizationAnalyticsPanel/);assert.match(reports,/تحليلات المتابعة/);});
test("PostgreSQL runner applies analytics after 040/041 and transfer assertions before analytics",()=>{const a=runner.indexOf("040_memorization_follow_up_notes.sql"),b=runner.indexOf("041_memorization_follow_up_scope_hardening.sql"),c=runner.indexOf("042_memorization_follow_up_analytics.sql"),d=runner.indexOf("memorization-follow-up-assertions.sql"),e=runner.indexOf("memorization-follow-up-transfer-assertions.sql"),f=runner.indexOf("memorization-analytics-assertions.sql");assert.ok(a>=0);assert.ok(b>a);assert.ok(c>b);assert.ok(d>c);assert.ok(e>d);assert.ok(f>e);});
