import { AlertTriangle, BarChart3, RefreshCw, RotateCcw, TrendingUp, Users } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { EmptyState, SectionHeader, StatCard } from "@/components/ui/app-primitives";
import { fetchMemorizationAnalytics, type MemorizationAnalyticsData, type MemorizationAnalyticsFilters } from "@/lib/memorization-analytics";
import { MEMORIZATION_FOLLOW_UP_CATEGORIES, MEMORIZATION_FOLLOW_UP_CATEGORY_LABELS, MEMORIZATION_FOLLOW_UP_PRIORITY_LABELS, MEMORIZATION_FOLLOW_UP_STATUSES, MEMORIZATION_FOLLOW_UP_STATUS_LABELS } from "@/lib/memorization-follow-up";

type Props={schoolId:string;branchId:string;classId:string;studentId:string;dateFrom:string;dateTo:string};
const arabicDateFormatter=new Intl.DateTimeFormat("ar-DZ",{dateStyle:"medium"});
function formatDate(value:string){return arabicDateFormatter.format(new Date(value+"T12:00:00"));}
function surahLabel(surahNumber:number){return "سورة رقم "+surahNumber;}
function StudentLink({studentId,studentName}:{studentId:string;studentName:string}){const [,setLocation]=useLocation();return <button type="button" onClick={()=>setLocation("/students/"+studentId)} className="font-bold text-[#17663B] underline-offset-4 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#2F855A]">{studentName}</button>;}

export default function MemorizationAnalyticsPanel({schoolId,branchId,classId,studentId,dateFrom,dateTo}:Props){
  const [analyticsFilters,setAnalyticsFilters]=useState<Pick<MemorizationAnalyticsFilters,"category"|"status"|"priority">>({category:"",status:"",priority:""});
  const [data,setData]=useState<MemorizationAnalyticsData|null>(null);
  const [loading,setLoading]=useState(true);
  const [errorMessage,setErrorMessage]=useState("");
  useEffect(()=>{let cancelled=false;setLoading(true);setErrorMessage("");void fetchMemorizationAnalytics(schoolId,{branchId,classId,studentId,dateFrom,dateTo,category:analyticsFilters.category,status:analyticsFilters.status,priority:analyticsFilters.priority,limit:10}).then(result=>{if(!cancelled)setData(result);}).catch(()=>{if(!cancelled){setData(null);setErrorMessage("تعذر تحميل تحليلات المتابعة ضمن نطاقك الحالي. لم تُجرَ أي تغييرات.");}}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[analyticsFilters.category,analyticsFilters.priority,analyticsFilters.status,branchId,classId,dateFrom,dateTo,schoolId,studentId]);
  const unresolvedCount=data?data.overview.openCount+data.overview.improvedCount:0;
  return <div className="space-y-5">
    <section className="rounded-2xl border border-[#E2EAE4] bg-white p-4 print:hidden"><SectionHeader title="فلاتر أخطاء الحفظ" description="هذه الفلاتر تخص ملاحظات المتابعة فقط، بينما تبقى فترة التقرير والفرع والحلقة والطالب من الفلاتر العامة أعلاه."/><div className="mt-3 grid gap-3 sm:grid-cols-3">
      <label className="text-xs font-bold text-[#53675B]">نوع الملاحظة<select value={analyticsFilters.category} onChange={event=>setAnalyticsFilters(current=>({...current,category:event.target.value as MemorizationAnalyticsFilters["category"]}))} className="mt-1 min-h-11 w-full rounded-xl border border-[#D6E2D9] bg-white px-3 text-sm"><option value="">كل الأنواع</option>{MEMORIZATION_FOLLOW_UP_CATEGORIES.map(category=><option key={category} value={category}>{MEMORIZATION_FOLLOW_UP_CATEGORY_LABELS[category]}</option>)}</select></label>
      <label className="text-xs font-bold text-[#53675B]">الحالة<select value={analyticsFilters.status} onChange={event=>setAnalyticsFilters(current=>({...current,status:event.target.value as MemorizationAnalyticsFilters["status"]}))} className="mt-1 min-h-11 w-full rounded-xl border border-[#D6E2D9] bg-white px-3 text-sm"><option value="">كل الحالات</option>{MEMORIZATION_FOLLOW_UP_STATUSES.map(status=><option key={status} value={status}>{MEMORIZATION_FOLLOW_UP_STATUS_LABELS[status]}</option>)}</select></label>
      <label className="text-xs font-bold text-[#53675B]">الأولوية<select value={analyticsFilters.priority} onChange={event=>setAnalyticsFilters(current=>({...current,priority:event.target.value as MemorizationAnalyticsFilters["priority"]}))} className="mt-1 min-h-11 w-full rounded-xl border border-[#D6E2D9] bg-white px-3 text-sm"><option value="">كل الأولويات</option><option value="1">{MEMORIZATION_FOLLOW_UP_PRIORITY_LABELS[1]}</option><option value="2">{MEMORIZATION_FOLLOW_UP_PRIORITY_LABELS[2]}</option><option value="3">{MEMORIZATION_FOLLOW_UP_PRIORITY_LABELS[3]}</option></select></label>
    </div></section>
    {loading&&<section role="status" className="grid min-h-32 place-items-center rounded-2xl border border-[#E2EAE4] bg-white"><span className="flex items-center gap-2 text-sm font-semibold"><RefreshCw className="size-4 animate-spin"/>جارٍ تحليل ملاحظات الحفظ...</span></section>}
    {errorMessage&&<p role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{errorMessage}</p>}
    {!loading&&data&&data.overview.observationCount===0&&<EmptyState title="لا توجد ملاحظات متابعة ضمن الفلاتر" description="غيّر الفترة أو نطاق الحلقة أو فلاتر النوع والحالة والأولوية."/>}
    {!loading&&data&&data.overview.observationCount>0&&<>
      <section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard label="ملاحظات المتابعة" value={String(data.overview.observationCount)} icon={BarChart3} tone="blue" hint={"لـ "+data.overview.studentCount+" طالب"}/><StatCard label="تحتاج متابعة" value={String(unresolvedCount)} icon={RotateCcw} tone="amber" hint={"مفتوحة "+data.overview.openCount+" · تحسنت "+data.overview.improvedCount}/><StatCard label="مواضع متكررة" value={String(data.overview.recurringSignatureCount)} icon={TrendingUp} tone="green"/><StatCard label="عالية الأولوية" value={String(data.overview.highPriorityUnresolvedCount)} icon={AlertTriangle} tone="red"/></section>
      <section className="grid gap-4 xl:grid-cols-2">
        <div className="rounded-2xl border border-[#E2EAE4] bg-white p-4"><SectionHeader title="أكثر أنواع الأخطاء" description="تجميع مشتق من الملاحظات الواقعة ضمن الفترة والفلاتر الحالية."/><div className="mt-3 space-y-2">{data.categories.map(row=><div key={row.category} className="flex items-center justify-between gap-3 rounded-xl border border-[#EDF2EE] p-3 text-sm"><div><p className="font-bold">{MEMORIZATION_FOLLOW_UP_CATEGORY_LABELS[row.category]}</p><p className="mt-1 text-xs text-[#718377]">{row.studentCount} طالب · {row.unresolvedCount} تحتاج متابعة</p></div><b className="text-lg">{row.observationCount}</b></div>)}</div></div>
        <div className="rounded-2xl border border-[#E2EAE4] bg-white p-4"><SectionHeader title="المواضع الأكثر تكرارًا" description="السورة ونطاق الآيات التي ظهرت فيها الملاحظة أكثر من غيرها."/><div className="mt-3 space-y-2">{data.locations.map(row=><div key={[row.surahNumber,row.ayahStart,row.ayahEnd].join("-")} className="flex items-center justify-between gap-3 rounded-xl border border-[#EDF2EE] p-3 text-sm"><div><p className="font-bold">{surahLabel(row.surahNumber)} · {row.ayahStart}–{row.ayahEnd}</p><p className="mt-1 text-xs text-[#718377]">{row.studentCount} طالب · {row.unresolvedCount} غير معالجة</p></div><span className="rounded-full bg-[#EEF7F1] px-3 py-1 font-bold text-[#17663B]">×{row.observationCount}</span></div>)}</div></div>
      </section>
      <section className="rounded-2xl border border-[#E2EAE4] bg-white p-4"><SectionHeader title="الطلاب الأعلى حاجة للمتابعة" description="ترتيب قراءة فقط حسب الملاحظات غير المعالجة والتكرار، ضمن صلاحياتك الحالية."/><div className="mt-3 grid gap-3 md:hidden">{data.students.map(row=><article key={row.studentId} className="rounded-xl border border-[#EDF2EE] p-4 text-sm"><StudentLink studentId={row.studentId} studentName={row.studentName}/><p className="mt-1 text-xs text-[#718377]">{row.className}</p><div className="mt-3 grid grid-cols-3 gap-2 text-center text-xs"><span>غير معالجة <b>{row.unresolvedCount}</b></span><span>متكررة <b>{row.recurringSignatureCount}</b></span><span>عالية <b>{row.highPriorityUnresolvedCount}</b></span></div></article>)}</div><div className="mt-3 hidden overflow-x-auto md:block"><table className="w-full min-w-[720px] text-right text-sm"><thead className="bg-[#F5F8F5] text-xs text-[#607368]"><tr><th className="p-3">الطالب</th><th className="p-3">الحلقة الحالية</th><th className="p-3">الملاحظات</th><th className="p-3">غير معالجة</th><th className="p-3">مواضع متكررة</th><th className="p-3">عالية الأولوية</th></tr></thead><tbody className="divide-y divide-[#EDF2EE]">{data.students.map(row=><tr key={row.studentId}><td className="p-3"><StudentLink studentId={row.studentId} studentName={row.studentName}/></td><td className="p-3">{row.className}</td><td className="p-3">{row.observationCount}</td><td className="p-3">{row.unresolvedCount}</td><td className="p-3">{row.recurringSignatureCount}</td><td className="p-3">{row.highPriorityUnresolvedCount}</td></tr>)}</tbody></table></div></section>
      <section className="grid gap-4 xl:grid-cols-2">
        <div className="rounded-2xl border border-[#E2EAE4] bg-white p-4"><SectionHeader title="اتجاه التحسن" description="حركات الحالة الموثقة في سجل التدقيق خلال الفترة المحددة."/>{data.trend.length===0?<p className="mt-3 text-sm text-[#718377]">لا توجد تغييرات حالة موثقة في هذه الفترة.</p>:<div className="mt-3 space-y-2">{data.trend.map(row=><div key={row.eventDate} className="rounded-xl border border-[#EDF2EE] p-3 text-sm"><p className="font-bold">{formatDate(row.eventDate)}</p><p className="mt-1 text-xs text-[#718377]">تحسن {row.improvedEvents} · تمت المعالجة {row.resolvedEvents} · عادت للمتابعة {row.reopenedEvents}</p></div>)}</div>}</div>
        <div className="rounded-2xl border border-[#E2EAE4] bg-white p-4"><SectionHeader title="أولوية المتابعة الآن" description="أحدث الملاحظات عالية الأولوية التي لم تُحل بعد."/>{data.recentHighPriority.length===0?<p className="mt-3 text-sm text-[#718377]">لا توجد ملاحظات عالية الأولوية ضمن الفلاتر الحالية.</p>:<div className="mt-3 space-y-2">{data.recentHighPriority.map(item=><article key={item.id} className="rounded-xl border border-[#EDF2EE] p-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><div><StudentLink studentId={item.studentId} studentName={item.studentName}/><span className="me-2 text-xs text-[#718377]">{item.className}</span></div><span className="rounded-full bg-red-50 px-2.5 py-1 text-xs font-bold text-red-700">تكرر ×{item.recurrenceCount}</span></div><p className="mt-2 font-semibold">{MEMORIZATION_FOLLOW_UP_CATEGORY_LABELS[item.category]} · {surahLabel(item.surahNumber)} · {item.ayahStart}–{item.ayahEnd}</p><p className="mt-1 text-xs leading-6 text-[#53675B]">{item.noteText}</p><p className="mt-1 text-[11px] text-[#89968E]">{formatDate(item.observedOn)}</p></article>)}</div>}</div>
      </section>
      <p className="flex items-center gap-2 rounded-xl bg-[#F5F8F5] p-3 text-xs text-[#607368]"><Users className="size-4"/>التحليلات قراءة فقط ومشتقة من سجل المتابعة؛ لا تُنشئ تقييمات أو توصيات آلية جديدة.</p>
    </>}
  </div>;
}
